### ISSUE TITLE
[sequencer] Bids should expire

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#1001]
There's no need to have a bunch of bids hanging around, we can put them into Redis with a 10 min expiry or so.

**Comment by jakekidd** [comment]
I'm not following the logic here. Are you saying we should delete bids after 10 mins bc they probably are invalid bids, or just to clean out the DB as we go?

Counterexample:
- Router A bids for a 2-router multipath transfer
- Nothing happens for 10 mins
- Router B comes online and bids for a 2-router multipath transfer

This would probs lead to some unexpected behavior. When it comes to deleting old bids, we should probs just track when a transfer has gone over 30 mins and/or has been reconciled... no sense in executing fast liquidity at that point.

**Comment by rhlsthrm** [comment]
I agree with you here. We should actually just remove bids that have been reconciled. I will change the scope of this task.

**Comment by alexwhte** [comment]
@rhlsthrm @jakekidd Is this a hard blocker to amarok public testnet/router integration?

**Comment by rhlsthrm** [comment]
It seems like we need to rescope this task to account for multipath CC @jakekidd @alexwhte. Will close and rescope around this later. It's not a blocker.
