### ISSUE TITLE
[sequencer] If all bids from auction attempt fail, remove from cache

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#1002]
Need to remove fully failed auctions from the cache. No point keeping them around.

**Comment by jakekidd** [comment]
What determines if a bid fails? If a multipath transfer between 2 routers fails, do both bids fail (e.g. what if only 1 of the two bids was faulty)?

I think we should address *why* bids (AKA `execute`s) are failing before we just toss out failing ones. That way we can avoid unnecessary work and log reasoning behind decisions to ignore certain bids. So before ever estimating gas, let's do some sanity checks.

So, why would a bid fail?
- The router (or one of the routers) has insufficient funds. For this, we should be checking the router's funds *before* estimating gas and/or sending the transfer. We should *not* just blindly call estimate gas on the whole `execute` tx.
- The signature is invalid. This is actually a genuine reason to throw out the bid! We should have an off-chain check in utils to make sure the signature is indeed valid; just something that mimics the on-chain check. We may want to wait on this until we have the relayer fees diff in.
- The relayer address is not whitelisted. We should always have a reference to who the relayers are for each chain. If we don't, then the chains (and the sequencer) were not configured properly.
- The asset is not whitelisted. Should be checked when we receive the bid.
- The router is not whitelisted. Should be checked when we receive the bid.

Can't think of any others, except maybe a bug in the contracts... which means that the *bid* is not the point of failure.
