### ISSUE TITLE
[router] Do not execute if Nomad is down

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#1007]
Check Nomad SDK:

> If you run 'checkHomes' on the SDK and provide it a list of networks, then you can access 'blacklist' value which is a set of Failed homes

**Comment by alexwhte** [comment]
@rhlsthrm  Do we need this error handling in Connext Bridge UI?

**Comment by rhlsthrm** [comment]
> @rhlsthrm Do we need error handling for this in Connext Bridge UI?
> 
> edit: nvm, commented in master #990

This needs a matching task in the SDK because the SDK should also implement this functionality.

**Comment by base0010** [comment]
After looking at the nomad sdk not convinced that checkHomes is going to give us the correct state of if the destination chain is processing nominally. Needs clarification, but a shared utility that keeps track of the latest block hash of a updater committed root. Then we can have simple logic to compare that to block hash of now. If there is a significant n block lag (tbd what this measure exactly should be and if it needs be dynamic) we know the destination chain is down.
