### ISSUE TITLE
[cache] Multiple bids per transferId

### ISSUE THREAD

**Issue by wanglonghong** [connext/nxtp#1013]
file: adapters/cache/src/lib/caches/auction.ts

Sequencer should be able to store multiple bids per transfer Id.  The sequencer can receive several bids from different routers for a specific transferId.  

==============================
 > public async getBidData(transferId: string): Promise<BidData | undefined> {
 >   const res = await this.data.hget(`${this.prefix}:bidData`, transferId);
 >   return res ? (JSON.parse(res) as BidData) : undefined;
 >  }
 
==============================
>   public async setBidData(transferId: string, data: BidData): Promise<number> {
>    return await this.data.hset(`${this.prefix}:bidData`, transferId, JSON.stringify(data));
> }

With ^^ above function, we can't store multiple bids per transferId, it just overwrites bidData whenever a new bid arrives at the sequencer. 

Here is the basic example to show how `hset`/`hget` basically works. 

> 127.0.0.1:6379> flushall
> OK
> 127.0.0.1:6379> hset bidData "0x111" "mock1"
> (integer) 1
> 127.0.0.1:6379> hset bidData "0x111" "mock2"
> (integer) 0
> 127.0.0.1:6379> hget bidData "0x111"
> "mock2"

 In order to solve this problem,  I think we have to generate keys with the router address and transferId. Its fine whatever doesn't overwrite the other routers' bidData.

**Comment by jakekidd** [comment]
`bidData` is basically the args for `Connext.execute`. It should only need to be stored once per transfer.

`bids` is what you're looking for - we store bids indexed by router. See the `upsertAuction` function.

**Comment by wanglonghong** [comment]
ok. I think I misread here. ty for letting me know.
