### ISSUE TITLE
[contracts] Admin functions

### ISSUE THREAD

**Issue by LayneHaber** [connext/nxtp#1038]
Should have additional admin functions for setting the:

- [x] `LIQUIDITY_FEE_NUMERATOR`
- [x] `LIQUIDITY_FEE_DENOMINATOR`
- [x] `tokenRegistry`
- [x] `relayerFeeRouter`
- [x] `executor`
- [x] `wrapper`

**Comment by liu-zhipeng** [comment]
I don't think we need a function to update `LIQUIDITY_FEE_DENOMINATOR`

**Comment by LayneHaber** [comment]
done in #1207
