### ISSUE TITLE
[ops] Deploy backend

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#1054]
Backend will consist of:
- Backend process that reads subgraph and saves data to Postgres DB.
- Postgres DB.
- REST API server.

**Comment by rhlsthrm** [comment]
Blocked by #1024

**Comment by alexwhte** [comment]
@rhlsthrm FY I marked as a blocker for public testnet announcement , not sure if accurate

**Comment by rhlsthrm** [comment]
> @rhlsthrm FY I marked as a blocker for public testnet announcement , not sure if accurate

Correct this is a blocker.
