### ISSUE TITLE
[ops] Deploy Lighthouse

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#1055]
Watcher is an isolated module that reads subgraph data and sends API requests to Gelato to execute transfers that have been reconciled but not executed.

**Comment by rhlsthrm** [comment]
@sanchaymittal can you share the PR for the watcher which is a blocker for this?

**Comment by jakekidd** [comment]
Did you mean Watchtower? lol

**Comment by rhlsthrm** [comment]
> Did you mean Watchtower? lol

Correct lol. Also I thought we could do this with Gelato but it seems like we can't actually because they don't react to events.

**Comment by carlomazzaferro** [comment]
Do we have some specs around this? Which PR implements lighthouse, which kind of networking it needs, and which env variables it must have?

@sanchaymittal @rhlsthrm

**Comment by sanchaymittal** [comment]
Done 🎉
