### ISSUE TITLE
As a developer, I want to fork a UI-starter that leverages the SDK

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#1098]
**Problem**
Users can start-up a UI out of the box to build an app, forking Coinhippo UI might have too much going on

**Ideas to solve this**
Add simple ui to the xapp starter kit. 
Demonstrate various uses of the transfer status utilities exposed by SDK.

**Acceptance Criteria**
[ ] Forkable and runnable UI out of the box
[ ] Tracking transfers through status
[ ] xcall fast and slow works 

**Other**
Austin Griffith down to show scaffold.eth and this could be a better integration point for devs 
Should this live in it's own repo? Depends if we need to test

**Comment by alexwhte** [comment]
Consider breaking out into two:
1. Scaffold  - P3 (Nice)
2. Internal testing one - P1 (Need)

**Comment by just-a-node** [comment]
Close as we will basically have this done with the chain abstraction UI template
