### ISSUE TITLE
Bridge fast transfers not executing correctly

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#1167]
some cases store bid but then say no auctions to execute (images below) 
is this weird, its storing tons of bids but doesnt seem to be executing any auctions
i just cleared cache and it started working
wondering if the cache is filling
would be weird theres not that much stuff
{"data":[{"service":"Relay","chain":"rinkeby","taskId":"0x87358a0dd1b099973dacc394eb89f1fa5a535a309fb6d6722e1722803bcc574b","taskState":"CheckPending","created_at":"2022-05-11T19:32:00.624Z","lastCheck":{"taskState":"CheckPending","message":"Execution Error","payload":null,"created_at":"2022-05-11T19:32:51.997Z","reason":"no error message"},"lastExecution":"2022-05-11T19:32:00.624Z"}]}

not seeing fast liq coming thru staging either: txn: 0x143c8afb4281e634b0a86577cfb0566207a67a6485932dca54c5fda38b18b0a3

![image](https://user-images.githubusercontent.com/37959170/167977618-9f28a5e8-d819-4634-9427-396716704866.png)

![image](https://user-images.githubusercontent.com/37959170/167977636-48c50d33-98ad-492f-a22b-10cf21d6ab99.png)

**Comment by sanchaymittal** [comment]
fixed in latest version!
