### ISSUE TITLE
As a bridge user, I should not get stuck if Nomad and/or destination chain is down

### ISSUE THREAD

**Issue by base0010** [connext/nxtp#1168]
This is a continuation of the cases from #1007 :

Problem: We're only covering part of the case "is nomad down on destination chain" by using checkHome(s) in nomad sdk (see 1007). 

This will report if destination chains are in a bad state, ie. "an "improper update" has been proven to the home, aka a freak reorg event or fraud."  but not if they are "down" insofar as updates to the destination have stopped all together. 

We can build a subgraph query to index the block number of the last on-chain updater event that was fired. Then compare that to the current block number, and have some maximum allowed difference before we consider the receiving chain "down" and put that into the sanity checks logic like 1007.

**Comment by alexwhte** [comment]
Per convo I'm moving this to closed as we met the core condition in https://github.com/connext/nxtp/pull/1130

Handling ALL use cases is a future optimization need

**Comment by alexwhte** [comment]
Note: No points this sprint 4 as it was already completed

**Comment by alexwhte** [comment]
Closing per hack
