### ISSUE TITLE
Add extra fields to backend

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#1181]
https://github.com/connext/nxtp/pull/1180#pullrequestreview-972168810

This is a bandaid fix. We need to update the backend to account for these fields.

Tasks:

- [x] Update DB schema to add extra columns for new fields
- [ ] Update parser methods
- [ ] Verify data from subgraphs correctly inserts

**Comment by preethamr** [comment]
@rhlsthrm  Zapatos 5.0.4 generates different `packages/agents/backend/poller/src/zapatos/schema.d.ts` should we upgrade ?

**Comment by rhlsthrm** [comment]
> @rhlsthrm Zapatos 5.0.4 generates different `packages/agents/backend/poller/src/zapatos/schema.d.ts` should we upgrade ?

Yes if there's an upgrade available let's go for it.
