### ISSUE TITLE
As a developer, I would like ARM and x86 build support

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#1188]
**Problem**
Users want to use ARM and x86

**Ideas to solve this**
We could add this functionality in a UI

**Acceptance criteria**
[ ]

**Other**
https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md

**Comment by carlomazzaferro** [comment]
closing in favour of https://github.com/connext/nxtp/issues/1724
