### ISSUE TITLE
As a lighthouse, I should not keep trying to execute transactions which will always fail

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#1266]
## Background

There can be xtransfers made which are never able to successfully execute on the destination domain. We need a way to mark them as "unresolvable" so that the lighthouse does not keep trying to execute.

## Definition Of Done

The lighthouse does not try to execute transfers forever which will not succeed.

I think we can do this in phases:

Phase 1: Expose a way to manually mark these txs and we can do it ourselves.
Phase 2: Use some intelligence to do this by checking revert messages, etc. Lighthouse can post to the backend directly to update the status.

**Comment by sanchaymittal** [comment]
fixed and merged.
