### ISSUE TITLE
Transaction issues /delays on Testnet

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#1269]
**Describe the bug**
Testnet users are starting to complain about long tx times. We should diagnose these txs and see why they are taking long. Either they are not settling at all or the UI is too delayed

https://discord.com/channels/454734546869551114/978722712686043188

**Expected behavior**
Transactions should not take this long to complete. 

**To Reproduce**
1. Go to https://amarok-testnet.coinhippo.io/TEST-from-gorli-to-kovan?amount=5
2. Bridge TEST from Gorli to Kovan
3. 

**Additional context**
Example: Everything is fine but take too long per transaction to successful.
0x1853fBc8D66372dA2f5dAA7422dBb77fC3Ac14eB
![image](https://user-images.githubusercontent.com/37959170/170551189-5e718ee9-e7b2-46cf-8f11-427c1db0e115.png)

**Comment by sanchaymittal** [comment]
Working on setting up a performance metrics for agents involved in the process to analyze the processing time at each stop.

**Comment by alexwhte** [comment]
@sanchaymittal  Did this get resolved?

**Comment by rhlsthrm** [comment]
This is due to a couple things:
- Sequencer freezing.
- Cartographer paging through thousands of txs.

**Comment by rhlsthrm** [comment]
Going to mark this as resolved. We have fixed the underling issues now.
