### ISSUE TITLE
Testnet transfers failing because cannot estimate gas

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#1270]
**Describe the bug**
Confirming a transfer from Gorli to Kovan failed because 'cannot estimate gas

**To Reproduce**
1. Go to https://amarok-testnet.coinhippo.io/TEST-from-gorli-to-kovan?amount=5
2. Submit transfer
3. It breaks and shows. this error 

**Additional context**
cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"code":-32603,"message":"execution reverted: ERC20: approve to the zero address","data":{"originalError":{"code":3,"data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002245524332303a20617070726f766520746f20746865207a65726f2061646472657373000000000000000000000000000000000000000000000000000000000000","message":"execution reverted: ERC20: approve to the zero address"}}}, method="estimateGas", transaction={"from":"0x6d91e35d502fb6F654992283e6E4f397fC23DC2c","to":"0xEC3A723DE47a644b901DC269829bf8718F175EBF","value":{"type":"BigNumber","hex":"0x00"},"data":"0x4156a883000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000800000000000000000000000003ffc03f05d1869f493c7dbf913e636c6280e0ff90000000000000000000000000000000000000000000000004563918244f4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006d91e35d502fb6f654992283e6e4f397fc23dc2c00000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000d0300000000000000000000000000000000000000000000000000000000000008ad0000000000000000000000006d91e35d502fb6f654992283e6e4f397fc23dc2c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.6.5)

**Comment by sanchaymittal** [comment]
This seems to be a bug on the UI side, where the signer address isn't updated before calling the approveIfNeeded(). Contact Coinhippo to fix this!

**Comment by sanchaymittal** [comment]
resolved and fixed.
