### ISSUE TITLE
Production testnet subgraphs and DB are out of sync.

### ISSUE THREAD

**Issue by preethamr** [connext/nxtp#1280]
**Describe the bug**
Transfer data in the DB and subgraph are out of sync for a prolonged period. `poller` poll loop not functioning properly.

**Expected behavior**
`poller` should not stall, and should produce more debug logs while in process.

**Additional context**
Production testnet subgraphs and DB are out of sync.

**Comment by sanchaymittal** [comment]
Was fixed and merged.
