### ISSUE TITLE
Cartographer not showing some router balances

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#1324]
https://api.thegraph.com/subgraphs/name/connext/nxtp-amarok-runtime-v0-rinkeby/graphql?query=query+MyQuery+%7B%0A++router%28id%3A+%220xc4eac3bfae3f3c951225c16848ddcab3d6a5abbf%22%29+%7B%0A++++assetBalances+%7B%0A++++++asset+%7B%0A++++++++adoptedAsset%0A++++++++blockNumber%0A++++++++canonicalDomain%0A++++++++canonicalId%0A++++++++id%0A++++++++local%0A++++++%7D%0A++++%7D%0A++%7D%0A%7D

This shows up on the subgraph but if I query cartographer:

```
GET {{postgrestUrl}}/routers_with_balances?address=eq.0xc4eac3bfae3f3c951225c16848ddcab3d6a5abbf
```

I only receive for domains Goerli and Kovan:

```json
[
  {
    "address": "0xc4eac3bfae3f3c951225c16848ddcab3d6a5abbf",
    "asset_canonical_id": "0x0000000000000000000000003ffc03f05d1869f493c7dbf913e636c6280e0ff9",
    "asset_domain": "2221",
    "router_address": "0xc4eac3bfae3f3c951225c16848ddcab3d6a5abbf",
    "balance": 10000000000000000000000000000,
    "local": "0x3ffc03f05d1869f493c7dbf913e636c6280e0ff9",
    "adopted": "0x3ffc03f05d1869f493c7dbf913e636c6280e0ff9",
    "canonical_id": "0x0000000000000000000000003ffc03f05d1869f493c7dbf913e636c6280e0ff9",
    "canonical_domain": "2221",
    "domain": "2221"
  },
  {
    "address": "0xc4eac3bfae3f3c951225c16848ddcab3d6a5abbf",
    "asset_canonical_id": "0x0000000000000000000000003ffc03f05d1869f493c7dbf913e636c6280e0ff9",
    "asset_domain": "3331",
    "router_address": "0xc4eac3bfae3f3c951225c16848ddcab3d6a5abbf",
    "balance": 10000000000000000000000000000,
    "local": "0x3ffc03f05d1869f493c7dbf913e636c6280e0ff9",
    "adopted": "0x3ffc03f05d1869f493c7dbf913e636c6280e0ff9",
    "canonical_id": "0x0000000000000000000000003ffc03f05d1869f493c7dbf913e636c6280e0ff9",
    "canonical_domain": "2221",
    "domain": "3331"
  }
]
```

**Comment by rhlsthrm** [comment]
Just to tack onto this issue, we should do what we discussed and have separate processes for the router balance polling vs the transfers polling.

**Comment by preethamr** [comment]
This is likely resolved after the `carto` refactor in `main`, TBD for `prod`

**Comment by alexwhte** [comment]
@preethamr  Is this good to close now?

**Comment by rhlsthrm** [comment]
> @preethamr Is this good to close now?

No it's not. I just looked into this with Preetham and found the issue. The issue is that we are only pulling the first 100 routers so anything past that will not get added to the backend, and therefore also the UI. We need to chunk up the subgraph queries to handle any amount of routers.

The fix is fairly straightforward and either myself or @preethamr will get it done this week.

**Comment by sanchaymittal** [comment]
Was fixed and merged
