### ISSUE TITLE
As a router, I should not be able to put in some ridiculous auction depth (far greater than bid length max)

### ISSUE THREAD

**Issue by LayneHaber** [connext/nxtp#1343]
**Describe the bug**
<img width="1130" alt="Screen Shot 2022-06-01 at 9 14 32 PM" src="https://user-images.githubusercontent.com/12769011/171545359-3c83a755-b366-49bd-901f-4e6c2bd61f99.png">

**Additional context**

**Comment by sanchaymittal** [comment]
completed in #1224
