### ISSUE TITLE
Error adding TEST token router liquidity

### ISSUE THREAD

**Issue by Tommy-R8** [connext/nxtp#1348]
"The execution failed due to an exception."

![image](https://user-images.githubusercontent.com/84744304/171637366-48af0f4e-2e19-4ff0-8f83-04e3d7a5f15a.png)

User said they hard refreshed and still couldn't get it to work. Also they said the error persisted through browser restart and wallet reconnection

**Comment by sanchaymittal** [comment]
<img width="1504" alt="Screenshot 2022-06-06 at 11 21 01 AM" src="https://user-images.githubusercontent.com/31698676/172089038-12db574b-9c47-4996-a9c9-5d206f143785.png">

just tested it out, and it seems to be working. Not sure why it was failing for user, possibly the network was different.
Next time let's ask him to copy the logs from the console.
