### ISSUE TITLE
Datadog not parsing JSON logs properly

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#1352]
Our logs are JSON but DataDog seems to not be parsing the JSON properly. However it seems like DD should automatically be parsing JSON: https://docs.datadoghq.com/logs/log_configuration/parsing/?tab=matchers

Need to investigate.

**Comment by rhlsthrm** [comment]
@carlomazzaferro I believe this is done, can you confirm?

**Comment by carlomazzaferro** [comment]
> @carlomazzaferro I believe this is done, can you confirm?

Correct, this is done
