### ISSUE TITLE
Stuck Transactions

### ISSUE THREAD

**Issue by Tommy-R8** [connext/nxtp#1354]
**Describe the bug**
A lot of stuck transactions going back several hours. Different chains and different routers. What's weird is that many are from evmos to other chains and are still pending. If it was a subgraph issue, they shouldn't show up in the explorer in the first place

**To Reproduce**
1. try to bridge
2. ??
3. you got stuck successfully

**Additional context**
![image](https://user-images.githubusercontent.com/84744304/171968722-53c20f80-2800-4626-b1eb-4f377d1965bc.png)

Example transactions:
https://connextscan.io/tx/0x3504eb04d68511c99001ec113b4a82e181c563c655f37845fbe30c647ac771d8
https://connextscan.io/tx/0x28110fa34a63c9862e93c1f32dc9b1320afbe35aaa328da0edf5842608e6d662
https://connextscan.io/tx/0xfb85baa6c2b8aac585e204ad33a1a2871ef7d488d7f00dc9a57554a3feab340e
https://connextscan.io/tx/0xf12bbdb93318ab343efa4ef09fe2161b749cf2cc31b6679ab17d6baec8ea5bfb

**Comment by Tommy-R8** [comment]
Update: Polygon subgraph might be dead.
![image](https://user-images.githubusercontent.com/84744304/171968892-d1ddf198-7606-4009-8575-2bf1eef99731.png)

Polygon prepare TX: https://polygonscan.com/tx/0x4f1123826bb29afa3fb7e31b8ca765200c5eea78dc48a362ae3ccdf3194c42f5
Connext TX: https://connextscan.io/tx/0xf0ec94d34cf2cd2bb48c218b4a73360a21be289209b19310b84725940f692b52

**Comment by Tommy-R8** [comment]
Update 2: Optimism subgraph might be dead too.
![image](https://user-images.githubusercontent.com/84744304/171968966-949ff775-b153-437e-b653-39802ba17ec7.png)

Optimism fulfill TX: https://optimistic.etherscan.io/tx/0x4645967878aa8b4b12cb1bfd317c8751eb5ea551e1e794ab29cf728ed08efdd2
Connext TX: https://connextscan.io/tx/0x938ba00df96fc8dec8208ddec069acd7a3ed3e038f6f66589a7e5c6ae0007d52

**Comment by Tommy-R8** [comment]
Update 3: BSC subgraph also??
![image](https://user-images.githubusercontent.com/84744304/171974833-57ee3a76-a347-4000-8d23-ee4bf992a768.png)

https://connextscan.io/tx/0x7a776242c0825ed4a4c8249ebfaf21084f89c029fcca0c4f14a59df36ea8bf30

**Comment by Tommy-R8** [comment]
Actually, looks like a front end issue on the explorer and the bridge
```
Error: No subgraphs available on this chain; unable to handle request.
    at c.request (https://connextscan.io/_next/static/chunks/pages/_app-8a52d249168d837e4ed8.js:215:87674)
    at async https://connextscan.io/_next/static/chunks/pages/_app-8a52d249168d837e4ed8.js:215:6174
    at async Promise.all (index 6)
    at async t.Subgraph.getActiveTransactions (https://connextscan.io/_next/static/chunks/pages/_app-8a52d249168d837e4ed8.js:215:6015)
    at async https://connextscan.io/_next/static/chunks/pages/_app-8a52d249168d837e4ed8.js:215:3274
```

**Comment by alexwhte** [comment]
fixed
