### ISSUE TITLE
Polygon volume miscalculated in Explorer (all-time)

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#1357]
**Describe the bug**
March 27 - April 2 is showing a massive spike in All-time view

**To Reproduce**
1. Go to  https://connextscan.io/
2. Change Volume to All-Time

**Additional context**
![image](https://user-images.githubusercontent.com/37959170/172019404-7004e6cb-8b17-4812-8363-180b87863c37.png)

**Comment by alexwhte** [comment]
Low pri due to Amarok - do not pick this up

**Comment by sanchaymittal** [comment]
<img width="1504" alt="Screenshot 2022-06-06 at 11 18 37 AM" src="https://user-images.githubusercontent.com/31698676/172088849-90ac80ce-1bf8-473e-b5f8-3d3c48c29704.png">

Seems to be fixed now.
