### ISSUE TITLE
Gnosis missing transaction

### ISSUE THREAD

**Issue by Tommy-R8** [connext/nxtp#1368]
**Describe the bug**
A transaction going from Gnosis to BSC is missing on the explorer and there are no special subgraph or CORS errors.

**To Reproduce**
1. Go to Connextscan
2. Search for the Gnosis TX 0x363ecf0d5238776660ed159d3fe5b2a1c4152260117805fb3ab3090350917856
Alternatively:
1. Go to Connextscan
2. Search for the Connext TX 0x71a9ffe0f747f557d06af66407193485f5f5b5c50ce4083c2d0477bd8eb8bed1

**Additional context**
Link to the prepare transaction on Gnosis https://blockscout.com/xdai/mainnet/tx/0x363ecf0d5238776660ed159d3fe5b2a1c4152260117805fb3ab3090350917856/logs
From the logs I pulled the transaction ID and tried looking it up on Connextscan and on LogDNA, found nothing special and the tx is missing from Connextscan.
https://connextscan.io/tx/0x71a9ffe0f747f557d06af66407193485f5f5b5c50ce4083c2d0477bd8eb8bed1

**Comment by Tommy-R8** [comment]
Note: The user input a wrong destination address of which he has no control of, so they'll wait for expiration in 72hs. The issue is not urgent.

**Comment by Tommy-R8** [comment]
More people with the same issue are coming to the Discord.

1. https://connextscan.io/tx/0xdf06e4fbe4d1a480de804817b81c32ef8147fe089024f7e5f2c3bd5fb856f6af
2. https://connextscan.io/tx/0x5b2ea32c93e3eaf4a374207c36875edb8eee6b231d0efd3f64d000c1df70df00

**Comment by rhlsthrm** [comment]
Found that Bware subgraph is stuck. Switched it for Graph subgraph. Should be resolved shortly.
