### ISSUE TITLE
Subgraph should not have duplicate nonce

### ISSUE THREAD

**Issue by preethamr** [connext/nxtp#1370]
**Describe the bug**

**To Reproduce**
If you see:
https://api.thegraph.com/subgraphs/name/connext/nxtp-amarok-runtime-staging-kovan/graphql?query=query+MyQuery+%7B%0A++originTransfers%28orderBy%3A+nonce%2C+orderDirection%3A+desc%2C+first%3A+100%29+%7B%0A++++transferId%0A++++nonce%0A++%7D%0A%7D

We have duplicate nonce:
```
{
  "data": {
    "originTransfers": [
      {
        "transferId": "0xbd27fe3822e37289bc66ba4364d8acbd2c8ebd26ec71f1669ad224078c8d3e2a",
        "nonce": "11"
      },
      {
        "transferId": "0x287c3d119ce4fb22505cee3060cbb7ce798ade585c33ee4c9c4ddeae05f7bd59",
        "nonce": "10"
      },
      {
        "transferId": "0xa4069f583e87f8d02bd37f3ee8c1041b8dbe09e9c926d9c7d23f0c3264a14ce8",
        "nonce": "9"
      },
      {
        "transferId": "0x62c7bc36e79072ffcaf9e14983e7e381da4273d20de93eb4d03a19f35a19f282",
        "nonce": "8"
      },
      {
        "transferId": "0x2765dcd6e3705802276883404aef299bc9690998a59ac1839acc65cc5919ffd5",
        "nonce": "7"
      },
      {
        "transferId": "0xe2e0b4f9de412480e3a72bd0eadb7caaac23195b5970640debbed42cb9c2448e",
        "nonce": "6"
      },
      {
        "transferId": "0x6312990bc4b577485b26291a7d01efb604add585a0901fe5f98315d67df5ea53",
        "nonce": "6"
      },
      {
        "transferId": "0xed388c88b22abec6878150d642d18eae7d52c1831bca529f5563c5b3ac0f127b",
        "nonce": "5"
      },
      {
        "transferId": "0xc4c90e680bbb1e47588a637a40e6dbaf66d4d5f6904aba1f24e5418bc68e853c",
        "nonce": "5"
      },
      {
        "transferId": "0xea6b3f1eca8196fedbdc9d63d61563376d5e80289a0b182635f6fbb8581a9337",
        "nonce": "4"
      },
      {
        "transferId": "0xba242677fe0255a9e7ea4529c6cd2bfcd77764882a44595639fc78494194dbb5",
        "nonce": "4"
      },
      {
        "transferId": "0x9841e1033d9724aac371382fddc58237ed98e6f7ef2773effddebdfd621ea631",
        "nonce": "3"
      },
      {
        "transferId": "0x0650b6df949c6bf7ebd03a9dda3e605d54e44271d11c1f9dcaa4cfee502433c6",
        "nonce": "3"
      },
      {
        "transferId": "0xe0f0c95366dd428980fcfc2e7064b02f617e962ae7d00840a1aa4da258ff1cf4",
        "nonce": "2"
      },
      {
        "transferId": "0x4616d1b0600b8cae912934788926757121739b814220f01fc2a7f3c47da38ba5",
        "nonce": "2"
      },
      {
        "transferId": "0xfd14ec5b10530fdc69dbdf9eb78db7358de3b172df1a65ab4e59225135359cc7",
        "nonce": "1"
      },
      {
        "transferId": "0x7add85afebb2f2baa1018320f24d086e8497886f487f3ab14bf9b9a352eed0a8",
        "nonce": "1"
      },
      {
        "transferId": "0xae74eef9d4934f9eeb0ca63b4a111e081d38faedcd0effeb8ed402d1ac69716c",
        "nonce": "0"
      },
      {
        "transferId": "0xa5d662de4201a0d3b98088f3f633846fd3887e23387a2e873ece03fdec539b7a",
        "nonce": "0"
      }
    ]
  }
}
```

**Additional context**
This was found only in Kovan staging subraph:
https://api.thegraph.com/subgraphs/name/connext/nxtp-amarok-runtime-staging-kovan

**Comment by jakekidd** [comment]
It seems like the subgraph is reading a history of stale XCalled events. Since we are using the diamond proxy pattern, the address is maintained across deployments, so the event history would also be maintained (by provider network). It's unclear to me why the storage nonce would be reset back to 0 on a subsequent deployment. Perhaps core architecture/proxy got redeployed, but I would think that would mean the address would change.

To fix, we *should* change the "startBlock" in `packages/deployments/subgraph/config/amarok-runtime-staging.json` to match the deployment block of the contract on kovan: `0xD9C3bc89e8B14a8B01481f0748e24d3d7fa18DB2`.

This does not seem to be a bug with the underlying contract code or the subgraph mapping.

**Comment by jakekidd** [comment]
The block number of the contract create seems to match what's currently set as the startBlock.

It appears that DiamondInit, one of the facet contracts, was redeployed at block 31982545:
https://kovan.etherscan.io/tx/0x02bb21a47bcc7117315887f721fcb6d0cd1f9e4958926f511c39c28379d58104

Which is > 31682492, the current "startBlock"

And this contract's `init` method resets the nonce to 0. The block number for this contract's deployment should be what we set the "startBlock" to in `packages/deployments/subgraph/config/amarok-runtime-staging.json` under kovan
