### ISSUE TITLE
As a log viewer I should see clean logs without startup logs for agents that restart constantly

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#1400]
**Problem**
There are lots of startup logs on the Cartographer and since we rearchitected it to restart constantly, it spits out a lot of pretty useless logs. 

**Ideas to solve this**
We should change the logging so it doesn't do so much of that.

**Acceptance Criteria**
[ ] X happens
[ ] Y happens

**Other**

**Comment by alexwhte** [comment]
@rhlsthrm Do we need more specifics to size this?

**Comment by sanchaymittal** [comment]
A lot of fixes has been done for better logging, let's open this again if it's still relevant
