### ISSUE TITLE
As a Datadog user I should only use live tail logs

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#1401]
We are running out of trial soon on DD, and our biggest expense is logs. For now, we can get by with live tail and not storing any logs. We need to completely revamp our logging strategy to optimize for DD, but for now we can completely turn off the log storage.

**Comment by just-a-node** [comment]
Wildcard exclusion filter applied to the main index (you must have at least 1 index defined). This effectively disables indexing. Should follow up with #1422 to enable archiving.
