### ISSUE TITLE
User funds sent to Fulfill Interpreter Contract

### ISSUE THREAD

**Issue by Tommy-R8** [connext/nxtp#1405]
**Describe the bug**
When the transaction was fulfilled, the funds were sent to the Fulfill Interpreter contract instead of the user destination address.

**To Reproduce**
1. Get tx fulfilled by Gelato
2. Funds were sent to Fulfill Interpreter (0x0e893A2ca06DA26a483D03C14a260847B218a231)

**Additional context**
TX Link: https://connextscan.io/tx/0x0ef0dd0b5e5f70e1b2fa2ee2117f1e65a3a9bbd8c1761d2be7122c399860437a
Fulfill tx on Fantom: https://ftmscan.com/tx/0x6595bdd8286f8eb57c4c449f9f5038ea170ed8ee3c9216b9d2dfd0287b616927
User destination address: 0x9acd14328badd3645b3a1b83e52200f28cdd133f
Fulfill Interpreter address: 0x0e893A2ca06DA26a483D03C14a260847B218a231

**Comment by Tommy-R8** [comment]
User passed a contract address with no calldata
![image](https://user-images.githubusercontent.com/84744304/173389066-3bcfa598-5970-42c5-aef1-7d48131f1687.png)
The contract they put in is a router

**Comment by alexwhte** [comment]
Paid w/ magic spell 
![image](https://user-images.githubusercontent.com/37959170/173975973-f4813815-e627-416a-8ecc-fe8ec50b0306.png)
