### ISSUE TITLE
As a router, I need to check to make sure Nomad updater update is correctly signed

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#1423]
**Problem**
Router currently does not check for updater fraud.

**Ideas to solve this**
Check updater signature on home chain before sending bid to sequencer.

**Acceptance Criteria**
[ ] If signature valid, proceed with bid.
[ ] If signature invalid, log error and hold off on bid.

**Other**
SDK should also show some kind of alert if this is the case?

**Comment by jakekidd** [comment]
more details in discord message thread https://discord.com/channels/454734546869551114/925716372707749938/986752407151214692

**Comment by alexwhte** [comment]
Check if fraud committed before fronting transfers

**Comment by alexwhte** [comment]
Closing per hack
