### ISSUE TITLE
Arbitrum Fee Error

### ISSUE THREAD

**Issue by Tommy-R8** [connext/nxtp#1425]
**Describe the bug**
User sent 10000 USDC from Fuse to Arbitrum, and only received 9770. 222 USDC went to a "EIP173ProxyWithReceive" contract in the fulfill transaction. This is different from the router bid fee estimation error because the router actually bid for 9993 USDC and didn't keep that 222 extra.

**To Reproduce**
1. Go to bridge to Arbitrum
2. Get a normal bid and fee estimation (around 7 USDC)
3. At the moment of fulfilling, get 222 USDC taken somehow

**Additional context**
Connext TX: https://connextscan.io/tx/0x90a892d6225da5542afc20a3307be2cab26671fb8afabeb83b73b35f10875aa2
Arbitrum fulfill TX: https://arbiscan.io/tx/0x67c2df1953278d240e9212bc88f94e63dd14c702f02265cd1fa73e07f8b02239
Contract address that received the missing funds: https://arbiscan.io/address/0x0ae392879a228b2484d9b1f80a5d0b7080fe79c2#code

![image](https://user-images.githubusercontent.com/84744304/173980492-b96f1912-e760-494a-9e24-eeb24cfc9595.png)

**Comment by Tommy-R8** [comment]
User also took a screenshot of the final amount to be received
![image](https://user-images.githubusercontent.com/84744304/173980775-c7c8e40a-7fd9-471d-8555-0d53369361c4.png)

**Comment by alexwhte** [comment]
Is this related? [#1403](https://github.com/connext/nxtp/issues/1403)

**Comment by Tommy-R8** [comment]
Relayer fee estimation issue with the following transaction from BNB Chain to Polygon

Connext TX: https://connextscan.io/tx/0x5cb6d14beabfdeeddc3f77b07172ba9700ad1f09faeb8e2ca165bde412aca944
Polygon fulfill TX: https://polygonscan.com/tx/0xdaf85d02f204f407ff68b6458286cde75ac420ae5a57b212c24bcaac427cd135

The relayer took 9.5 DAI when it should take like 5 cents at most

**Comment by Tommy-R8** [comment]
Another Arbitrum transaction where the decoded bid shows a reasonable received amount but for some reason, the explorer shows MUCH less, and the fee taken was 442 USDC

https://connextscan.io/tx/0x621257fc8a64b7ea6ad224a7d33be50cd535f62a8b60613cb021beac36b2cab2

![image](https://user-images.githubusercontent.com/84744304/174457961-b43d9e16-631e-4b0c-afca-42b78bb522fc.png)
![image](https://user-images.githubusercontent.com/84744304/174457965-16c14799-cd57-4c5d-9bb4-9e6d7b7e594b.png)

**Comment by Tommy-R8** [comment]
Another issue with Arbitrum

Connext TX: https://connextscan.io/tx/0x57b51217f0b72f6c305de820e0bd70bf1ea478d61480643e8a01b74f3fe78eb3

**Comment by Tommy-R8** [comment]
Arbitrum to Optimism

Connext TX: https://connextscan.io/tx/0x182ab2329969bd78cedb6fdf4860e6500ef1dbaf17c95e9ce42db6642a15a324

**Comment by wanglonghong** [comment]
We had an option to exclude arbitrum network but it didn't work properly. Linked pr will get it working.

**Comment by Tommy-R8** [comment]
Evmos to Arbitrum

Connext TX: https://connextscan.io/tx/0x0e95eaa80655ae98e808b76ac59fad85c1e622efcb65a0fe6eeedbdb19fc49b4

**Comment by Tommy-R8** [comment]
Ethereum to Arbitrum

Connext TX: https://connextscan.io/tx/0x20421427250ec58cd55d7b4b4658d527f818d8af7614f90f0ab6a26b2a7111ad

**Comment by Tommy-R8** [comment]
Polygon to Arbitrum

Connext TX: https://connextscan.io/tx/0x0d8e3c806396eea582eaec9359f76812be016f825f57ed3ca631b07845234f0f

**Comment by Tommy-R8** [comment]
Polygon to Arbitrum

Connext TX: https://connextscan.io/tx/0xdc43f38bb04a2502ceee36421351c7a59c6d512a8d9873180264e41da729ac63

**Comment by Tommy-R8** [comment]
BSC to Arbitrum

Connext TX: https://connextscan.io/tx/0x294bdde093ee4bf9134208e7e8bfb24c26c12d2fbdef34cec6d7ff4916d86696

**Comment by Tommy-R8** [comment]
Ethereum to Arbitrum

Connext TX: https://connextscan.io/tx/0x6c36f38928ad674ff468b42c6ccbcf6955d0bb76059a3278571e8316a1ddcbfe

**Comment by Tommy-R8** [comment]
Ethereum to Arbitrum

Connext TX: https://connextscan.io/tx/0xa72a58ec3c49b7debf153c719680b4669ca6cc18ef03a1a9a3aac6675bf04ec9

**Comment by Tommy-R8** [comment]
Polygon to Arbitrum

Connext TX: https://connextscan.io/tx/0xc118737b4626f32c6f059097f9669bf0c73163aedc089d30e25d2607932a458c

**Comment by Tommy-R8** [comment]
Arbitrum to Optimism. This tx was made after the fix but I don't know if the router is patched yet. Maybe investigate this one

Connext TX: https://connextscan.io/tx/0x3e2e3bce2341e8d4b011e14cede389e97cca2769f859515ce02498bc34a14d58

**Comment by Tommy-R8** [comment]
Arbitrum to Optimism.

Connext TX: https://connextscan.io/tx/0x0a8feaa93e913a1651f8a25bc7bda4ae62e58f1ae55ed0f6d2065afb040ee4d9

**Comment by Tommy-R8** [comment]
Polygon to Arbitrum.

Connext TX: https://connextscan.io/tx/0xaaaa34ab540f6ed70149efbd6b8fbb4d576b55d01394994e7954a29f5c85d0da

**Comment by Tommy-R8** [comment]
Optimism to Arbitrum.

Connext TX: https://connextscan.io/tx/0x2721debecf88a7d3416e33ac148066651de3f0d5ab555fa9c5baf823c8221809

**Comment by Tommy-R8** [comment]
Arbitrum to Polygon. This time it's a different router

Connext TX: https://connextscan.io/tx/0x7afeb58f7eccbf55eb9aabf42387c130303d60c4a2a4c638cb238668309e84e1

**Comment by Tommy-R8** [comment]
Fantom to Arbitrum.

Connext TX: https://connextscan.io/tx/0xe3bd45807fa4426a71404dd9ff4e3eb6afdef7e49ab54c9949f23fea60d7573f

**Comment by Tommy-R8** [comment]
Fantom to Arbitrum.

Connext TX: https://connextscan.io/tx/0x6f7d7fedf533d948d2ac44807160493b6e24a2c3f515c4e09ac59b9b132aea8a

**Comment by Tommy-R8** [comment]
Optimism to Arbitrum.

Connext TX: https://connextscan.io/tx/0x904f113467edb95b4cd2311d53e38273083dbb93a1a4e18e7f05f986cf726eb0

**Comment by sanchaymittal** [comment]
Was fixed during sprint 5-6
