### ISSUE TITLE
As a user, my transfer data should not have gaps

### ISSUE THREAD

**Issue by preethamr** [connext/nxtp#1430]
**Describe the bug**
Queries form `cartographer` to subgraphs use timestamps to checkpoint. This checkpoint mechanism because of quirks of how queries to subgraph work, are causing data gaps.

**To Reproduce**
1. Start with a fresh DB
2. Sync with prod testnet config
3. See data gaps

**Comment by sanchaymittal** [comment]
Was completed in sprint 5
