### ISSUE TITLE
As a team, we want better logs to help pinpoint the source(s) of transaction latency

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#1432]
**Problem**
Sometimes transfers are slower than expected and we don't have a great way to see where the issue is / which agent is the culprit
example: https://github.com/connext/nxtp/issues/1431

**Ideas to solve this**
Add better logging on key events and/or with agents to enable visibility into our weak points

**Acceptance Criteria**
[ ] We can look at logs from a slow transaction and at minimum pinpoint which agent(s) and/or step(s) of transfer on backend caused the delay
[ ] Y happens

**Other**

**Comment by sanchaymittal** [comment]
It is done with new log query setup in data dog
