### ISSUE TITLE
As a router, I should be able to figure out how to handle the error from ankr.

### ISSUE THREAD

**Issue by wanglonghong** [connext/nxtp#1440]
https://app.datadoghq.com/logs?event&from_ts=1655794610152&index=&live=true&query=service%3Arouter+env%3Atestnet+stage%3Astaging&to_ts=1655795510152

Rouer keeps exiting in case of provider error. It happens on nomad context when checking domains if they're whitelisted or not

**Comment by wanglonghong** [comment]
https://app.datadoghq.com/logs?event&from_ts=1655794610152&index=&live=true&query=service%3Arouter+env%3Atestnet+stage%3Astaging&to_ts=1655795510152

Rouer keeps exiting in case of provider error. It happens on nomad context when checking domains if they're whitelisted or not

**Comment by wanglonghong** [comment]
https://github.com/connext/nxtp/issues/1545

**Comment by alexwhte** [comment]
@wanglonghong  Are we actively working on this still?

**Comment by wanglonghong** [comment]
@alexwhte  it should be closed. Nomad sdk version update should def fix it
