### ISSUE TITLE
As a dev, I need message queues deployed as part of CI

### ISSUE THREAD

**Issue by preethamr** [connext/nxtp#1474]
**Problem**
Message queues used in `router` and `sequencer` agents, should be provisioned on `production` and `staging` environments, with appropriate config.

**Ideas to solve this**
Add new terraform modules, that can automate this deploy and integrate it as part of Github CI 

**Acceptance Criteria**
[ ] MQ is available in `production` for `router` use-cases
[ ] MQ is available in `staging` for `router` use-cases
[ ] MQ is available in `production` for `sequencer` use-cases
[ ] MQ is available in `staging` for `sequencer` use-cases

**Other**

**Comment by carlomazzaferro** [comment]
WIP https://github.com/connext/nxtp/pull/1493

**Comment by rhlsthrm** [comment]
This is done.
