### ISSUE TITLE
As a dev, I want to estimate gas usage for pool functions

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#1480]
**Problem**

SDK users should be able to estimate gas for the following pool operations:
- addLiquidity()
- removeLiquidity()
- swap()

**Ideas to solve this**

The existing SDK functions already have an `estimateGas` parameter. Setting this to `true` should return a gas estimate rather than a `TransactionRequest`.

**Acceptance Criteria**
[ ] addLiquidity() can be gas estimated 
[ ] removeLiquidity() can be gas estimated 
[] swap() can be gas estimated

**Comment by alexwhte** [comment]
Archiving per convo

**Comment by alexwhte** [comment]
closed per convo layne/rahul
