### ISSUE TITLE
As a cartographer, my health should be monitored

### ISSUE THREAD

**Issue by preethamr** [connext/nxtp#1482]
**Problem**
If `cartographer` is in bad health we might not know.

**Ideas to solve this**
`cartographer` should have monitoring and alerting setup.
- Based on CPU and memory usage

**Acceptance Criteria**
[ ] CPU and memory based monitoring
[ ] CPU and memory based alerting

**Other**

**Comment by sanchaymittal** [comment]
Is this done? @alexwhte @carlomazzaferro

**Comment by rhlsthrm** [comment]
Yes this is done since we are using scheduled tasks to control.
