### ISSUE TITLE
As connext eng, I want a script that does a check-up on asset configuration for all supported chains.

### ISSUE THREAD

**Issue by jakekidd** [connext/nxtp#1492]
**Problem**
Just want something that takes inventory step-by-step, with minimal input, checking to make sure whether an asset is set up on each chain. I'm imagining it produces a list of each chain and whether the asset is not set up, partially set up, or fully configured for that chain (in the console)

**Ideas to solve this**
Script that takes an input of a canonical ID and then just making sure the asset's configured correctly. If the asset is partially configured, mark all parts where the configuration is messed up.

As an additional bonus, might be nice to hook in the Deployer keys and then just have it "autofix" the problems... but that could be a second follow-up task from this one.

**Comment by alexwhte** [comment]
Closing per grooming with Layne/Rahul
