### ISSUE TITLE
As a user, I want to see segmented Amarok Volume and Transfer metrics

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#1495]
**Problem**
User at least wants the same homepage metrics in Amarok https://connextscan.io/ (by period, by chain, by asset)
With the right data availability, there are more important use-cases that require further segmentation i.e. where routers are seeking to ingest this into internal dashboards 

**Ideas to solve this**
Make transaction count and volume data available 
Completed Volume and transfer data can be fetched by the below vectors:

- date 
- (by time period daily, weekly, monthly, all-time)
- asset
- chain
- router_id
- wallet_id / contract_id
- path

Additional ask: Split by message "category" <--- maybe a separate/addon request? 
- $-value vs 0-value transfers 
OR
- crypto vs. NFTs vs. votes vs. <other types> 

**Acceptance Criteria**
- User can see volume and transactions in connectscan by period, chain, asset https://testnet.amarok.connextscan.io/
- Routers can see volume and transactions for their ID
- Abilty to break out slow path from fast path
- Reconciliation should not be included in topline volume 

**Next steps**
[ ] Create SQL queries
[ ] Design and expose API endpoint to get this data
[ ] (Optional) SDK wrapper
[ ] Test it in UI

**Other**
https://docs.google.com/spreadsheets/d/1WUv0ye5Ev0fO3w2ejVYRRyCHhTXi8W5OG6vMCJwTkhk/edit#gid=1298285392

https://www.notion.so/connext/Overview-Tab-3c316149368d47ceb2289818b8c8ada6

**Subtasks**

- #1697
- #1684 
- #1693

**Comment by rhlsthrm** [comment]
This should be broken out into multiple tasks. #1684 is the beginning of this.

**Comment by sanchaymittal** [comment]
After reviewing the work done in last pr which merged to main now, a sub-list tasks is created and posted here: https://www.notion.so/connext/Metrics-24cdd08b722a447a9b4a2c541975eb03
