### ISSUE TITLE
If slippage fails ensure execute retries and user can bump 

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#1497]
**Problem**
Users can specify slippage limits in the UI. If the limits are exceeded during the transfer, funds can get "stuck" on destination

**Ideas to solve this**
We should notify the user allow them to: 
Re-submit execute with higher slippage (can we recommend the level needed?)

**Acceptance Criteria**
- [ ] User is notified of the slippage failure
- [ ] User is presented options to proceed
- [ ] User can bump slippage
- [ ] Execute retries automatically (if they bump OR not)

**Comment by alexwhte** [comment]
Hardest part is tracking the failure

**Comment by alexwhte** [comment]
P0

**Comment by just-a-node** [comment]
There are two parts to this:
1) https://github.com/connext/nxtp/issues/2094: cancel
2) https://github.com/connext/nxtp/issues/1878: bump

**Comment by alexwhte** [comment]
closing as dupe 2094

**Comment by alexwhte** [comment]
closing as dupe 2094
