### ISSUE TITLE
F:022 Caused through walletconnect.

### ISSUE THREAD

**Issue by oswy-cpu** [connext/nxtp#1518]
**Invalid Signature while trying to claim with walletconnect (Bridge Wallet)**

**To Reproduce**
1. Connect wallet to connextscan with Bridge Wallet (https://www.mtpelerin.com/bridge-wallet) through WalletConnect
2. Try to claim and sign in Bridge Wallet
![f022](https://user-images.githubusercontent.com/74738120/179219921-85f63566-a47e-478b-9a01-91d4cb19e0bd.png)

**Additional context**
I haven't checked with other wallets via WalletConnect. The user cannot import the seed phrase into the metamask, has to wait for the expiration date.

**Comment by rhlsthrm** [comment]
Hi, this is not a wallet connect issue, this is a wallet signature issue. Can you please try claiming from connextscan.io?

**Comment by sanchaymittal** [comment]
Considering transaction must had a conclusion in 3 days on it's creation, this issue should have been resolved.
