### ISSUE TITLE
As a user, I can monitor transfers and their statuses in ~realtime

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#1540]
**Problem**
Users and Connext should know at scale where transfers are and be able to segment this data. For example, a wallet/user or a router should be able to see only their transfers. 

NOTE: It looks like most of this available maybe?
https://testnet.amarok.connextscan.io/tx/0xb375e734bd2eab450061bd0ca828bdbc0dbb9066e7980b95e6be2dc57fc487ab
 If so, please comment and rescope this issue, for example, if we only need the 'stuck' status better handled. 

**Ideas to solve this**
Data is made available with ability to segment 
MVP Status = 
- pending (xcall, execute, reconcile)
- completed (all stages completed)

Not mvp IF we can somehow monitor ourselves
- stuck (slippage_limit, relayer_gas_limit, _something_else_wrong(chain down?, nomad down?) NON-MVP_ 

**Acceptance Criteria**
- [ ] Users able to see where their transfers are (their own transfers statuses)
- [ ] Routers are able to see where their transfers are
- [ ] Data availability latency is <1min

**Other**
https://docs.google.com/spreadsheets/d/1WUv0ye5Ev0fO3w2ejVYRRyCHhTXi8W5OG6vMCJwTkhk/edit#gid=1298285392

**Comment by alexwhte** [comment]
If this should be broken into more than one request, please comment this and explain why/how

**Comment by sanchaymittal** [comment]
Implementation addressed in #1689
