### ISSUE TITLE
As a router, I want to pick up the transfers with enough relayerFee paid on the origin domain

### ISSUE THREAD

**Issue by wanglonghong** [connext/nxtp#1578]
Problem

The transfers are being bridged even though they didn't pay the relayer fee on the origin domain. routers should be able to pick up such transfers.

Ideas to solve this

**Comment by alexwhte** [comment]
@wanglonghong  Is this a bug?
Just as / fyi , bugs can just be statements like

"Transfers not picking up enough relayer fee on origin domain" 

Does not need the "as a __, I want..." :)

**Comment by wanglonghong** [comment]
I've discussed this with @rhlsthrm. we don't need to handle it on the router side. I wanna close this issue.
