### ISSUE TITLE
[router] 4.11 New auction validation

### ISSUE THREAD

**Issue by LayneHaber** [connext/nxtp#158]
> This finding highlights a collection of issues with the `handleNewAuction`. The code and coding style appears fragile. Validation should be strictly enforced, debugging code should be removed or disabled in production and protective measures should be taken from abusive clients.

**Comment by rhlsthrm** [comment]
Missing validation:
- Check zero-value bids (i.e. make sure there is profit for the router).

**Comment by jakekidd** [comment]
https://github.com/connext/nxtp/pull/178
