### ISSUE TITLE
BSC Mainnet is deployed and tested

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#1655]
## Problem
BSC is possibly in scope of our public beta launch, depending on complexity.
Connector added with Defi Wonderland here https://github.com/connext/nxtp/pull/1766

Note per @LayneHaber  
Defi wonderland tested the connector logic, but I just don’t know if you need to kick off a processing tx on mainnet

## Ideas to solve this
Add full stack support for BSC

- [x] Deploy contracts
- [x] Subgraphs
- [x] Change config
- [ ] Any liquidity provisioning 

## Acceptance Criteria
- [ ] Bridging to and from BSC works fast path
- [ ] Bridging to and from BSC works slow path
- [ ]

**Comment by sanchaymittal** [comment]
@alexwhte 
This task is blocked now!
- contracts are deployed but multichain connector needs contract updates to get working which are already pointed out in audits

**Comment by liu-zhipeng** [comment]
https://github.com/connext/nxtp/pull/2630
