### ISSUE TITLE
As a router, I should post bids

### ISSUE THREAD

**Issue by preethamr** [connext/nxtp#1671]
**Describe the bug**
During load tests, it was found that there were no bids sent to sequencer, for some of the valid transfers/xcalls.

**To Reproduce**
1. Initiate over a thousand transfers,
2. Notice that some of the transfers were never routed.

**Additional context**

Example transfer IDs in staging, which have no `router` logs in DD:

0x2cdbec54e1c9a69fb4f7d7a97ac4c22ca80bb4538e72c8534b203dd5b8a81001
0x71ab4c6ad2a1dd4de2838e33eed3d9a082d50071b98fa4e42bfae70bdf807618
0xd4ab5b380988c4d2f372b3732263f0e683ff1b9da11f4d15a825a64b00ddf79e
0xacfdefd3fd06f55fe974f2c6b15d2882f555214729ab73b1a71dac41b7499cf3
0xa22f9bd79286d06f61d3111f45b19a2dd465a492b21ce983cef928415dd20ce1
0x471a75719d1bd378e084bf7f08085ce834dde29272888ec8e1d22c677e87ca96
0xd9e2cdeb2606d47848d9e99660dbc8f5de9db03b906099170997a7201f55546a
0xa62c6d67e10176636fd7d1d89f634d2d13d22d444dc534e10c889b48b917c4a4
0xd54f9149a4c5580b8e8e2a53b4dd0d2eb943cf8f95cfdb5896b6d07c065d8a87
0xba9de139ebd8c3aca598c97ee8547793bae94589ba5ff1b77aae6e07f349b387

**Comment by sanchaymittal** [comment]
closing this after going through the logs, let's reopen this if we find another instance.
