### ISSUE TITLE
Insufficient checks in nxtp-utils v0.1.38

### ISSUE THREAD

**Issue by mathiasmoeller** [connext/nxtp#1683]
**Describe the bug**
When Connext disables a chain on their end but a developer still tries to request the subgraph for it. The whole nxtp-sdk dies. This error can not be caught as it happens asynchronously.

The problematic lines are the following: https://github.com/connext/nxtp/blob/v0.1.38/packages/utils/src/fallbackSubgraph.ts#L295-L296

`response.data` is not an Array and it does not contain `"No subgraph for"`. However, it is `"We don't keep track of the health of one or more of the chainIds you requested"`.

This makes `...response!.data.map` on line 304 break.

it can easily be fixed by checking for `Array.isArray`:
`const healthEndpointSupported =
        response && response.data && Array.isArray(response.data) && response.data.length > 0 && !response.data.toString().includes("No subgraph for");`

I didn't manage to create a PR for this, since the code doesn't exist on the current repository version anymore.

Thanks a lot already!

**Additional context**
This happened now on our end a lot due to the fact that EVMOS, Moonbeam and Moonriver were disabled by Connext

**Comment by rhlsthrm** [comment]
Hi @mathiasmoeller thanks for reporting! By the way, the code is on the branch called `legacy`!

**Comment by sanchaymittal** [comment]
As of now for legacy we have updated the chainData with all networks. Will be enabled on API in future with flexiblity to disable the network param.
