### ISSUE TITLE
As a dev, I need e2e to check all registered assets for setup validity

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#1707]
**Problem**

Current e2e test in CI only considers the TEST ERC20 token. As we add assets, e2e should also check validity of the setups for other assets as well.

**Ideas to solve this**

Grab deployment addresses for all registered assets and check that the local <> remote mappings obtained through subgraph are correct.

**Acceptance Criteria**

- [ ] e2e checks setup validity for all registered assets

**Other**

**Comment by alexwhte** [comment]
covered in init script
