### ISSUE TITLE
Load tests E2E

### ISSUE THREAD

**Issue by preethamr** [connext/nxtp#1711]
**Problem**
We need to include load testing in local e2e and CI e2e.

**Ideas to solve this**
Configure concurrency and scale of load tests during e2e integration tests,  such that config drives the environment creation, and execution of a test plan.

These are the sub tasks:
- [x] https://github.com/connext/nxtp/issues/1718
- [x] https://github.com/connext/nxtp/issues/1719
- [x] https://github.com/connext/nxtp/issues/1720
- [ ] https://github.com/connext/nxtp/issues/1721

**Acceptance Criteria**

- [ ] Concurrent transfers are validated as part of e2e
- [ ]  A summary of load test is generated

**Comment by alexwhte** [comment]
closing in favor of [As a team, we have sufficient testing & related processes to launch](https://github.com/connext/nxtp/issues/2146)
