### ISSUE TITLE
Set up Gelato Relayer tasks to regularly submit messages cross-chain & additionally validate messaging off-chain

### ISSUE THREAD

**Issue by jakekidd** [connext/nxtp#1714]
**Problem**
In the Interim AMB Messaging flow, the Relayer agent is relied upon for 
![AMB flow](https://user-images.githubusercontent.com/37907740/184258521-6d3b98cd-752d-4b40-99b1-ad71ad7e3b48.png)

Two components to this problem:
1. Relayers need to be told what to do and when to do it.
2. Relayers need to be funded.

**Ideas to solve this**

For problem (1) we should write a backend task to occasionally ping the relayer to do certain scheduled activities. We can schedule the activities up front using a Gelato Task in the on-chain contracts, or we could just use the relayer API - either way is fine. This should be a part of lighthouse - it aligns well with lighthouse responsibilities and doubles up on our current infra (so we don't have to bootstrap yet *another* agent).

For (2) we'll need to have a Gelato Vault regularly funded. This is fairly straightforward in of itself, but there's a bit of complexity here since we're obvi going to be doing things on multiple chains. We need to have some sort of alert system set up to let us know when we need to refill the Vault.

----------
## Spec / Subtasks

EDIT: The following subtasks have been simplified to use Gelato Relayer tasks instead. The Gelato API serves the purpose of automating this tasking to be executed regularly. Instead, we need the following tasking to be completed:

- [x] **`sendRoot` task** (see Step 2 in the Diagram) #1738 
- [ ] **`propagateRoot`  task** (see Step 3 in the Diagram) #1745 
- [ ] **`proveAndProcess`** #1761 
- [ ] **Root validation**
  - Make sure AMB messaging system does not commit fraud by regularly checking roots before Gelato tasks are carried out.
  - Routers could validate these roots themselves before submitting fast liquidity transfers.
- [ ] **Gelato Vault Management**
  - This task should be fairly straightforward. Set up a Gelato vault for paying Relayers on all the chains we support, however that works. Ideally, have a script to bootstrap that, maybe?
  - Configure the vault in Lighthouse, assuming it needs to be referenced in the API call.
  - Actually fund the vault with ETH, MATIC, whatever

----------
**IMPORTANT NOTES FOR YOUR CONSIDERATION: OPTIMIZATIONS, ETC**
NOTE 1: There is a bit of a race condition / optimization problem I suspect we'll run into with Subtask A and B above.

- Let's say User A is bridging from Opti => Polygon, and User B is bridging Mainnet => Polygon.
- User A send the xcalls and the outboundRoot gets updated on Opti. After an hour, the outboundRoot gets sent out.
- The outboundRoot for Opti currently will take 7 days to arrive for the AMB.
- After 6.9 days elapse, User B by coincidence sends their xcall, which updates outboundRoot for mainnet.
- The outboundRoot for mainnet gets sent out an hour later - *right before the the inbound root from Opti was going to arrive!*
- Had we waited just a little longer, we could have aggregated the root on mainnet to include User A's call, and send *both* to Polygon.

Annoying. Maybe this can be patched a bit by just making the window for Subtask B longer than the one for Subtask A. I.e. outboundRoots on mainnet (the hub) take 8 hours before sent out, whereas outboundRoots on other networks take only 1 hour. Would also make sense economically since ETH expensive!

Ideally we would have these window lengths weighted by native token price and gas price and batch size (a constraint problem), e.g. wait just a lil longer than an hour if there's only 1 or 2 txs in a batch... but it's probably sufficient to stick to estimates for the time being.

----------
NOTE 2: It *is* possible for no messages to be delivered to a chain. In current design, we actually just spam aggregate root updates out to all chains, even if there are no messages intended for ChainX, it will still receive the updated aggregate root. Kind of annoying. Maybe we can fix this?

----------
NOTE 3: Do all AMBs automatically handle calling `Connector.receiveRoot` for us? That *is* the xchain calldata we are sending through the AMB, but the question here is whether the AMB just makes that "verified call" available *or* has a relayer system for automatically calling it for us..... does this vary by chain?? Will we need to get relayers to do this in some cases??

**Comment by LayneHaber** [comment]
Wanted to drop [this](https://github.com/ethereum-optimism/optimism/blob/b70872149d98f9b14e2b15f74f9d08de75bb8b6e/packages/contracts-periphery/config/drippie/ethereum.ts#L23-L48) here as a reference for using [Drippie](https://dev.optimism.io/drippie-how-optimism-automates-ethereum/) to keep Gelato vaults funded
