### ISSUE TITLE
enrollCustom does not emit events

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#1715]
**Describe the bug**

The `enrollCustom` function does not emit events so the subgraph state doesn't accurately reflect custom representations. This causes offchain agents to be unable to retrieve the correct assets. 

**To Reproduce**
1. Setup new asset
2. Call `enrollCustom` to register the new asset as the new representation in the lookup tables
3. Try to transfer the new representation with `xcall`
4. Router subscriber will error with "Unable to get asset" on execute
5. XCall stalls forever

**Additional context**

See `transferId: 0x90410c48109664efa8a73d4ad01fdedb5ba3876ad6f34d49e5806623cfc0a388` for an example using madWETH from Rinkeby -> Goerli.

[The relevant DD logs](https://app.datadoghq.com/logs?query=%40requestContext.transferId%3A0x90410c48109664efa8a73d4ad01fdedb5ba3876ad6f34d49e5806623cfc0a388&cols=%40params.transferId%2C%40requestContext.origin&event=AQAAAYKD4ucNXXwRUwAAAABBWUtENHVuOEFBQUhycy1hWTdlckZnQUI&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1660011312635&to_ts=1660270512635&live=true)

**Comment by rhlsthrm** [comment]
I don't think we need to change this, we should be able to get all the info we need from our own events in setupAsset.

**Comment by LayneHaber** [comment]
no longer needed as we are emitting the local asset in `setupAsset`
