### ISSUE TITLE
As a dev, I need to be able to submit valid merkle proofs

### ISSUE THREAD

**Issue by LayneHaber** [connext/nxtp#1729]
**Overview**
We need to migrate the Merkle tree tracking all outbound messages to a separate contract to allow for easier upgrades

Currently the merkle trees and proofs are non-functional for both the `RootManager` and `Connector` contracts.

There should be two separate trees: the outbound message tree on the `Connector`, and the aggregate message tree on he `RootManager`.

The `Connector` contract should be able to prove the inclusion of an `outboundRoot` in the `aggregateRoot` as well as the `message` in the `outboundRoot`

**Steps**
From epic #1808 
- [x]  Create the `Merkle` contract that allows public reads, but restricted writes. Should have the ability for the owner to update the writing address
- [x]  Update `SpokeConnector` to have a reference to a `Merkle` contract instead of inheriting it
- [x]  Update the `RootManager` to have a reference to a `Merkle` contract (no inherits)

**Additional context**
The `Connector` contracts have logic for maintaining an outbound message tree, as well as for proving inclusion of a message in a tree root. The `RootManager` is missing all merkle functionality

**Comment by jakekidd** [comment]
@sanchaymittal added proof utils in TS: https://github.com/connext/nxtp/pull/1910
