### ISSUE TITLE
As a dev user, I want to be able to bypass the rollup delay

### ISSUE THREAD

**Issue by LayneHaber** [connext/nxtp#1730]
**Problem**
Right now, the `Optimism` and `Arbitrum` connectors use the default AMB bridge to execute passing the `outboundRoot` to the `RootManager`. This means the messages will have to be processed after the rollup delay elapses (7 days).

**Ideas to solve this**

- Enforce a modest delay on our contracts
- Include proofs for the messaging a la default AMB contracts

**Acceptance Criteria**

- [ ] Message can be proven against rollup state root
- [ ] Message inclusion proof can happen on the rollup connector
- [ ] `outboundRoot` can be propagated to `RootManager` in <7 days

**Other**

**Comment by alexwhte** [comment]
split out into two issues
