### ISSUE TITLE
Error creating NxtpSdkConfig

### ISSUE THREAD

**Issue by HenryHengZJ** [connext/nxtp#1757]
**Describe the bug**
Using @connext/nxtp-sdk@0.2.0-beta.17. When create NxtpSdkConfig, ran into error: `No domainId was found for the following chains: 0, 3, 10, 25, 56, 69, 97, 100, 122, 128, 137, 250, 288, 1285, 2221, 9001, 43113, 43114, 42161, 42170, 421611, 192837465, 1666600000;` `Continuing without indexing these chains.` `No Connext contract address for domain 3331.`

**To Reproduce**
1. Create NXTPConfig:
```
const nxtpConfig: NxtpSdkConfig = {
      logLevel: "info",
      signerAddress,
      chains: {
            "1111": {
		"assets": [
		     {
			"name": "TEST",
			"symbol": "TEST",
			"address": "0x3FFc03F05D1869f493c7dbf913E636C6280e0ff9"
		     },
		     {
			"name": "madWETH",
			"symbol": "TWETH",
			"address": "0xF25927315D101aC04C631878570152658defa7Db"
		     }
		],
	        "providers": ["https://rinkeby.infura.io/v3/d2560cac8f5645fba802260cf1f8c777", "https://rpc.ankr.com/eth_rinkeby"]
	    },
	    "3331": {
		"assets": [
		     {
			"name": "TEST",
			"symbol": "TEST",
			"address": "0x26FE8a8f86511d678d031a022E48FfF41c6a3e3b"
		      }
		 ],
		"providers": ["https://goerli.infura.io/v3/d2560cac8f5645fba802260cf1f8c777"]
	     }
       },
       network: 'testnet',
       environment: 'production'
   };
```
3. `const {nxtpSdkBase} = await create(nxtpConfig);`

**Comment by rhlsthrm** [comment]
This is not a bug and does not block anything from happening.

**Comment by rhlsthrm** [comment]
What is your issue? Everything should work as intended even though this is logged.

**Comment by HenryHengZJ** [comment]
Was following the [SDK Quickstart](https://docs.connext.network/developers/sdk/sdk-quickstart), when execute `yarn xtransfer` error was thrown `No Connext contract address for domain 3331`.
Tracing back to source code, looks like its using this [json](https://raw.githubusercontent.com/connext/chaindata/main/crossChain.json) in function `getChainData()`. From the json file, Goerli has domainId of `"1735353714"` instead of `"3331"` which was specified in Nomad. Replacing that fixes the issue. I can see `xCall transaction created` from the log.
However the transaction failed, example [tx](https://rinkeby.etherscan.io/tx/0x552ea32bbfa2c85c094314b7e732fe26bf75e1a48faa81b39cdf306c1c7d5b3a) on Rinkeby. But this is a separate issue.
