### ISSUE TITLE
As a dev, I want to use an intuitive default for transactingAsset for calldata-only xcalls

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#1786]
**Problem**

Add support for setting `transactingAsset: address(0)` in params for a calldata-only xcall. Right now we revert if it's set to `address(0)`. 

**Acceptance Criteria**

- [ ] Allow `address(0)` for `transactingAsset` param
- [ ] Enforce that `transactingAmount: 0` if `transactingAsset: address(0)`

**Other**

**Comment by sanchaymittal** [comment]
@just-a-node address zero means native asset, so we can't exactly add revert cause on L1 native asset is going to be this.

**Comment by just-a-node** [comment]
> 

I meant that right now we are reverting if it's set to `address(0)`, updated.
