### ISSUE TITLE
As a dev user, I need a simpler `xcall` Interface

### ISSUE THREAD

**Issue by LayneHaber** [connext/nxtp#1807]
**Problem**
Right now `xcall` is incredibly difficult to use (has way too many parameters):

```ts
CallParams memory callParams = CallParams({
      to: to,
      callData: "", // empty here because we're only sending funds
      originDomain: originDomain,
      destinationDomain: destinationDomain,
      agent: msg.sender, // address allowed to execute transaction on destination side in addition to relayers
      recovery: msg.sender, // fallback address to send funds to if execution fails on destination side
      forceSlow: false, // option to force slow path instead of paying 0.05% fee on fast liquidity transfers
      receiveLocal: false, // option to receive the local bridge-flavored asset instead of the adopted asset
      callback: address(0), // zero address because we don't expect a callback
      callbackFee: 0, // fee paid to relayers; relayers don't take any fees on testnet
      relayerFee: 0, // fee paid to relayers; relayers don't take any fees on testnet
      destinationMinOut: (amount / 100) * 97 // the minimum amount that the user will accept due to slippage from the StableSwap pool
    });

    XCallArgs memory xcallArgs = XCallArgs({
      params: callParams,
      transactingAsset: asset,
      transactingAmount: amount,
      originMinOut: (amount / 100) * 97 // the minimum amount that the user will accept due to slippage from the StableSwap pool
    });

    connext.xcall(xcallArgs);
  }
}
```

**Ideas to solve this**
We should target the following interface instead:

```ts
connext.xcall{value: fees}(
  to: to,
  callData: "", // empty here because we're only sending funds
  destinationDomain: destinationDomain,
  asset: asset, // renamed for simplicity
  amount: amount, // renamed for simplicity
  destinationMinOut: (amount / 100) * 97 // the minimum amount that the user will accept due to slippage from the StableSwap pool
);
```

Which means removing the following parameters:

- `originDomain`
- `agent`
- `recovery`
- `forceSlow`
- `receiveLocal`
- `callbackFee` and `relayerFee`
- `originMinOut`

and renaming:
- `transactingAsset` -> `asset`
- `transactingAmount` -> `amount`

*Removing `recovery`*
Update the contract to no longer take in encoded data directly, but instead send funds to the to address and call an interface. Instead of accepting abi-encoded calldata, we will require implementers to implement some interface. This allows us to transfer funds directly to the to address, and then call the interface function instead of trying to allow the user to specify a recovery address that can receive destination-chain funds on their behalf.

*Removing `receiveLocal`*
Should not have `receiveLocal` in the `CallParams`, and instead should have a separate, simpler function that allows you to indicate you would like to receive the local assets. This is needed for liquidity providers as well as routers, but should not pollute the `XCall` interface.

*Expanding `agent`*
The `agent` parameter and `forceReceiveLocal` functions are used to handle the edgecase where a user experiences sustained high slippage on the destination chain. The current design allows a user-specified address (the agent) to call `forceReceiveLocal` on their behalf, which allows them to receive the local asset. Once the local asset is received its likely users will either (a) swap and take on higher slippage or (b) send back to the origin. Instead, we should enshrine these options on chain, and allow the user to update their transaction to allow for higher slippage.

*Enforce a BPS `slippage`*
A transfer will hit AMMs up to twice within its lifecycle. Currently, we have slippage defined on both of these swaps. Instead, we should use a singular `destinationMinOut`. This can be enforced on the origin chain as well, and if the slippage is hit on the destination chain, then the `revert` path should be used.

*Removing `callbackFee` and `relayerFee`*
A transfer will hit AMMs up to twice within its lifecycle. Currently, we have slippage defined on both of these swaps in raw amounts. Instead, we should use a singular `slippage` representing the cumulative BPS loss you would take on the amount of adopted asset supplied to `xcall`. To enforce this properly, the amount and `originDecimals` would have to be passed through to the destination chain via the `transferId` generation.

*Removing `callback`*
Description: Instead, focus on nested xcalls (see #1704). There’s a lot of uncertainty about how to handle callbacks, and what people will use them for. This gives us the space to implement the feature correctly without carrying tech debt indefinitely.

**Acceptance Criteria**

- [x] #1809
- [x] #1818
- [x] #1819
- [x] #1824
    - [x] Remove `Executor`
    - [x]  Define interface
    - [x]  Call interface using `safeCall`
    - [x]  Update `CallParams` [offchain]
    - [x]  Update subgraphs [offchain]
    - [x]  Update all existing integrations [integrations]
- [ ] #1834
    - [x]  Remove `forceReceiveLocal`
    - [x]  Update `CallParams` + subgraphs
    - [x]  Add a function to bridge local for advanced users
- [x] #1877
    - [x]  Remove `forceReceiveLocal` function
    - [x]  Implement `forceUpdateSlippage` function
    - [ ]  Implement `revert`
    - [ ]  Ensure `execute` and `reconcile` cannot happen once a transaction has been `reverted`
    - [x] Rename `agent` because nobody likes my names :( 
- [x] #1835
    - [x]  Remove `originMinOut`
    - [x]  Remove `destinationMinOut`
    - [x]  Update the `CallParams` to include `slippage`
    - [x]  Update the `transferId` generation to include the `originAmount` and `originDecimals`
    - [x]  Update the `ExecuteArgs` to include added `transferId` fields
    - [x]  Update slippage enforcement on the `xcall` AMM swap to be the `slippage`
    - [x]  Update slippage enforcement on the `execute` AMM swap to be the `slippage` from the `originAmount` in proper decimals
- [ ] #1832
    - [x]  Remove the `PromiseRouter`
    - [x]  Remove the `callback` from the `CallParams`
    - [x]  Update the `execute` function to not call a `callback`
    - [x] Update `relayerFee` to be assigned as the `msg.value` of the message, without any changes to how the `relayerFee` is claimed
- [x] #1887
- [ ] #1914
- [ ] Update quickstart examples
- [ ] Update docs
- [ ] Update partners

**Other**

- [Design Rationale](https://www.notion.so/connext/Connext-Sucks-705f0a0e8f9b4f6ea7193f5fbf276267)
- [Task Masterlist](https://www.notion.so/connext/Task-Masterlist-2ef41facb2c749b38201e19ac8f05355)

**Comment by alexwhte** [comment]
@LayneHaber @ArjunBhuptani @liu-zhipeng @jakekidd Since this is iin the Done column, I'm closing this for tracking burndown
