### ISSUE TITLE
As a agent, I don't want to have connext address hardcoded for local chains.

### ISSUE THREAD

**Issue by wanglonghong** [connext/nxtp#1823]
**Problem**
The agents have connext addresses hardcoded for local chains (1337, 1338). That would be better to make them configurable so that whenever deployed addresses are changed, we will not update the source code

**located at getEnvConfig function of router, sequencer, and lighthouse**

**Ideas to solve this**
Make them configurable in config.json/.env or whatever is fine

**Comment by rhlsthrm** [comment]
Fixed in `connector-subgraph`.
