### ISSUE TITLE
Lighthouse needs to submit merkle proofs to proveAndProcess

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#1911]
Currently this is mocked out, use a merkle lib to generate proofs and pass them into the proveAndProcess function.

Subtask of #1808

**Comment by jakekidd** [comment]
See this issue for a great explanation on how to implement this!

https://github.com/connext/nxtp/issues/1923

**Comment by rhlsthrm** [comment]
Duplicate of https://github.com/connext/nxtp/issues/1923
