### ISSUE TITLE
As a Swap user, I need to be able to swap assets in the UI

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#1919]
**Problem to solve:**
User need to be able to swap assets in the UI 
https://amarok-testnet.coinhippo.io/swap/ETH-on-optimism

**Recommended Solution:**
NOTE NEED TO VERIFY WHAT WORKS ALREADY FIRST

**Acceptance Criteria:**
1. There are funds/assets supported for swapping
2. Pool has enough to enable swapping
3. Swap UI can fetch correct information
4. User can swap assets and receive correct resulting asset on same chain

**Comment by just-a-node** [comment]
Keep open for UI testing
