### ISSUE TITLE
As a user, I still want to bridge to Cronos with CRO native token support added during/after Amarok release

### ISSUE THREAD

**Issue by A-Keyboard** [connext/nxtp#1949]
**Problem**
With the release of Amarok soon, some chains like Cronos will not be supported

**Ideas to solve this**
Leave Cronos support for a few more weeks running on NXTP, and add support for $CRO, the native token, for bridging between Ethereum/Cronos

**Impact**

This is a massive opportunity for Connext, as Cronos is organizing a big NFT event, and they will use us as their official/first bridge that supports CRO crosschain transfers.

**Other Notes**
Potentially requiring some routers to keep supporting NXTP and providing $CRO, $USDC & $USDT liquidity

**Comment by alexwhte** [comment]
@A-Keyboard Can you comment on the impact of this? It doesnt really support any of our goals this half and not sure how to really evaluate what it will do for Connext

**Comment by alexwhte** [comment]
Adding to sprint to ONLY whitelist $CRO on nxtp-v1

**Comment by rhlsthrm** [comment]
Done.

**Comment by gotjoshua** [comment]
will connext add full support for CRO chain bridging?
