### ISSUE TITLE
Reconcile not happening on Optimism-Goerli -> Goerli

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#1982]
**Describe the bug**

We should have transactions reconciled in this direction. 

**To Reproduce**
1. Do an xcall from Optimism-Goerli -> Goerli
2. See that it executes but never reconciles

**Additional context**

**Comment by preethamr** [comment]
This is probably not happening in `staging`
Likely root cause is this revert in `_handleTransferHook`:



![Image](https://user-images.githubusercontent.com/1195648/193367300-cd0c24ee-2205-4769-9a3b-8407c0ba8b64.png)
