### ISSUE TITLE
As Connext, I want a zero-config way to configure deployments on staging and prod

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#1993]
**Problem**
The current init script is great, but requires a lot of config knowledge. If any of the config is not set up correctly, the script will incorrectly configure the contracts.

**Ideas to solve this**
Build in some defaults that are hardcoded into the script which we can access by running commands like:
```
$ init-connext --network goerli --env staging
```

**Acceptance Criteria**

- [ ] Init command is capable of running with hardcoded defaults for staging and prod, across all the networks we support.

**Other Notes**
Would be cool to take this opportunity to rebuild the init script using Foundry's [Solidity scripting](https://book.getfoundry.sh/tutorials/solidity-scripting).

**Comment by sanchaymittal** [comment]
fixes #2045
