### ISSUE TITLE
[contracts] Optimism

### ISSUE THREAD

**Issue by LayneHaber** [connext/nxtp#200]
Reconcile OVM contracts with mainnet. See if we can merge the two

**Comment by rhlsthrm** [comment]
There's a branch this is working in, not sure if we need to actually do this. The process for deploying would be:
- Switch to branch
- Build, deploy
- Export
- Cherry pick commit with exported deployment back to main

**Comment by LayneHaber** [comment]
Okay, open to closing this in favor of #229
