### ISSUE TITLE
Pooling on Optimism-Goerli broken

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#2009]
**Describe the bug**
Pooling WETH/nextWETH is not working for me

> cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABL...rome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:17:83886%22%7D, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.1

**To Reproduce**
1. Go to https://amarok-testnet.coinhippo.io/pool/ETH-on-optimism
2. Pool WETH and nextWETH
3. See error

**Screenshots**
![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/776af6d6-48b9-44f8-af1b-523ae222b931)

**Comment by just-a-node** [comment]
Fixed on staging - retest on prod once updates are deployed.
