### ISSUE TITLE
[bug][Contracts] owner should be able to call removeConnector() 

### ISSUE THREAD

**Issue by sanchaymittal** [connext/nxtp#2071]
**Describe the bug**
removeConnector() is only restricted to Watcher Role, owner should also be able to call the function as well.

Changing the modifier to OnlyOwnerOrWatcher should fix this behavior.

![image](https://user-images.githubusercontent.com/31698676/195271545-11a7935e-080f-4d0f-9fed-febb845ac218.png)

**To Reproduce**

**Expected behavior**

**Version:**

**Additional context**

**Screenshots**

**Comment by liu-zhipeng** [comment]
`addWatcher(owner address)` will fix this issue!

**Comment by liu-zhipeng** [comment]
we decided to add owner address to watcher list manually!

**Comment by liu-zhipeng** [comment]
https://github.com/connext/nxtp/issues/2091
