### ISSUE TITLE
Zero asset transfers with 0 amount errors out

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#2132]
**Describe the bug**
Sending an xcall with `asset = address(0)` and `amount = 0` should work.

**To Reproduce**
1. Send xcall with `asset = address(0)` and `amount = 0`
2. Check logs in DD
3. See that router-subscriber errors on `ParamsInvalid`, `/origin/assets/transacting - must have required property 'asset'`

**Expected behavior**
Should be able to handle this case (e.g. calldata-only xcalls).

Update: 0-value transfers should be considered as slow path only. Make router ignore 0-value transfers on fast execution.

**Version:**

**Additional context**

**Screenshots**

**Comment by wanglonghong** [comment]
https://github.com/connext/nxtp/pull/2137

**Comment by wanglonghong** [comment]
zero asset transfers should be able to get bridged in a fast path

https://discord.com/channels/992549151134982234/993950198529282158/1034754343037050941
