### ISSUE TITLE
 Add calculation of transfer price impact

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#2151]
## Problem
We should show the impact of their transfer on slippage. Price impact refers to the change in price directly caused by your own trade itself.

## Proposed Solution
See if we can use subgraph for this, otherwise use the `calculateSwap` function on the StableSwap contract.

## Acceptance Criteria
- [x] Price impact is calculated for swaps
- [x] Price impact is calculated for pool deposits
- [x] Price impact is calculated for pool withdraws
- [x] Calculation can be fetched by xApps through SDK

**Comment by just-a-node** [comment]
https://github.com/connext/nxtp/pull/2572
