### ISSUE TITLE
As a team, we need to fix all of the issues raised in the spearbit audit

### ISSUE THREAD

**Issue by LayneHaber** [connext/nxtp#2152]
**Describe the bug**
See comments in PRs to [this](https://github.com/spearbit-audits/connext-nxtp) repo.

**Additional context**
Audit goes through the 4th.

**All audit fixes should base off of `2152-spearbit-audit-fixes` branch!**

Every comment/issue should have a separate PR! Auditors should be able to point to a single commit (i.e. the PR merge commit) where the named issue was fixed.

If there's multiple comments regarding the same issue (like using custom errors), then it's okay to have them all refer to the same PR.

**Comment by jakekidd** [comment]
https://github.com/connext/nxtp/pull/2199

**Comment by jakekidd** [comment]
https://github.com/connext/nxtp/pull/2209

**Comment by jakekidd** [comment]
https://github.com/connext/nxtp/pull/2210

**Comment by jakekidd** [comment]
https://github.com/connext/nxtp/pull/2211
