### ISSUE TITLE
Stableswap data in subgraph

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#2174]
# Context

We need a subgraph to represent StableSwap data in a way that can be queried.

# Definition of Done

- [ ] Entities for balances of liquidity are available.
- [ ] Entities for swap fees collected are available.
- [ ] Other metrics required?

**Comment by just-a-node** [comment]
@sanchaymittal graph build is breaking with these changes atm

**Comment by sanchaymittal** [comment]
@just-a-node Just tested and deployed subgraph v0. It's working!
