### ISSUE TITLE
Able to view critical pool and swap metrics in the UIs

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#2185]
## Problem
We don't have full clarity into exact metrics to show and hide in Pool and Swap yet, nor is it working

## Acceptance Criteria
- [ ] User can at least see Pool TVL and Volume (24h)
- [ ] User can at least see Swap impacts similar to bridging 

## Solution
TBD

**Comment by just-a-node** [comment]
Closing in favor of #2102
