### ISSUE TITLE
[router] Provider functions to txservice

### ISSUE THREAD

**Issue by LayneHaber** [connext/nxtp#219]
[These](https://github.com/connext/nxtp/blob/main/packages/router/src/adapters/subgraph/provider.ts) functions should be converted to `txservice` reads, and all `txService` reads should likely go through the `contractReader` entity for consistency.

Interested to hear @rhlsthrm s opinion on the structuring

**Comment by rhlsthrm** [comment]
Absolutely these should be part of `txservice`.
