### ISSUE TITLE
Bridge UI 'cannot descstruture originDomain...'

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#2208]
**Describe the bug**
https://discord.com/channels/454734546869551114/909827059373723648/1034450925034668072

**To Reproduce**
1. Try to bridge on testnet
**Additional context**

**Screenshots**
![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/e5c99a4b-db95-4b49-b624-3dfe76ea86b2)

**Comment by sanchaymittal** [comment]
fixed!
