### ISSUE TITLE
Set up Connext Relayer

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#2254]
We need to begin load testing Amarok ASAP to see how it performs under stress, so we are aiming to do a 48hr test
Given recent GETH issues with Gelato they are paused, we are using our own relayer instead for this 

## Acceptance Criteria
- Connext relayer is setup for Amarok testnet 
- Relayer funded with enough GETH gas for 48 hours of testing 
- execute works with Connext relayer on hub<-> spoke and spoke<->spoke
- messaging layer calls (send, propagate, proveAndProcess, processRoot) are working

## Summary
UPDATE: A bug was found that revealed that we were processing the same messages repeatedly (https://discord.com/channels/992549151134982234/1034886488183275571/1034891216833232937), causing the heavy costs that prompted this issue. Regardless, proceeding with outlining tasking below.

Task tracking with the relayer is done using Redis. Tracking for tasks is pretty clean - each will have a uuid (same as gelato).

To request that the relayer call a method, you call endpoint POST /relays/:chainId
JSON params:
```ts
export const RelayerApiPostTaskRequestParamsSchema = Type.Object({
  to: Type.String(), // contract address
  data: Type.String(), // calldata
  fee: RelayerApiFeeSchema, // the fee paid on the sending side, tracked in the DB. we should make sure to supply this correctly for accounting!
});
```

**You should get a task ID back from this request - same as gelato!** (Write that down, write that down!)

Later, in a polling loop, we execute tasks. See `packages/agents/relayer/src/bindings/relays/index.ts` for details on that execution.

To check an inflight task's details, just hit up the endpoint  GET /tasks/:taskid

### On Relayer Side

- Currently the relayer parses input data to make sure this is an `execute` transaction. We can comment this out and make it so the relayer will accept any calldata as input and execute it. `packages/agents/relayer/src/lib/operations/tasks.ts`
- The relayer endpoint for creating a new task is not secured with an API key or admin key or anything. It's simple enough to add an API key, and probably all the security we should need for testnet purposes. The griefing vector we need to secure against is simply using the relayer to execute arbitrary txs, draining GETH. `packages/agents/relayer/src/bindings/server/index.ts`
- Get a relayer agent running LIVE **with a redis instance as well!**

Optional for Consideration:
- Are we paying fees for `execute` calls? Should we be collecting those fees at a later point? Probably doesn't need to be in scope for this issue, but we want to make sure we've done proper accounting if testnet ETH needs to be claimed later.

### On Consumer Side
Follow the instructions in the Summary section above to basically substitute using Gelato with using a designated Connext relayer. Please NOTE that we should REALLY configure this, and not just have some "fallback" behavior between the two that causes constant delays (due to calling Gelato first, task failing, then resorting to Connext relayer).

Places we'll need to be submitting to Connext relayer:

- Lighthouse:
    - `processRoot` (AMB request for Opti bridge)
    - `propagate` (RootManager on hub)
    - `send` and `proveAndProcess` (SpokeConnectors on spokes)
- Sequencer: `execute`

**Finally, don't forget to whitelist relayer EOA!**
**ALSO NOTE: Relayer code is NOT tested: there are NO unit tests for relayer agent. Unfortunately this likely means there will need to be some live debugging done, and we'll have to watch it closely for errors. Or we could take the time to do unit tests... tough call.**

**Comment by jakekidd** [comment]
https://github.com/connext/nxtp/pull/2256

**Comment by rhlsthrm** [comment]
Removing this from the sprint @alexwhte. This is no longer high priority considering Gelato will be back up.
