### ISSUE TITLE
Router liquidity not showing up for optimism testnet

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#2265]
**Describe the bug**
See title.

**To Reproduce**

1. Go to explorer: https://testnet.amarok.connextscan.io/router/0xd2ad711861ab345977b7379c81165708c8717ff1
2. See router liquidity is 0 on Opt

**Expected behavior**
Router has plenty of liquidity.

**Version:**

**Additional context**

**Screenshots**

**Comment by sanchaymittal** [comment]
fixed
