### ISSUE TITLE
[compiling] Problem when install the package Assembly Script

### ISSUE THREAD

**Issue by alfredolopez80** [connext/nxtp#230]
Hi, guys

I detect a problem with the version of the repo Assemble Script, in the main branch using version 0.6 and is not available right now.

Proposal:
Change de version from v0.6 to v.19.11 (the last one)
Original:
```
  "resolutions": {
    "assemblyscript": "git+https://github.com/AssemblyScript/assemblyscript.git#v0.6",
    "@nomiclabs/hardhat-ethers": "https://registry.npmjs.org/hardhat-deploy-ethers/-/hardhat-deploy-ethers-0.3.0-beta.10.tgz"
  }
```
Proposal:
```
  "resolutions": {
    "assemblyscript": "git+https://github.com/AssemblyScript/assemblyscript.git#v0.19.11",
    "@nomiclabs/hardhat-ethers": "https://registry.npmjs.org/hardhat-deploy-ethers/-/hardhat-deploy-ethers-0.3.0-beta.10.tgz"
  }
```

**Comment by rhlsthrm** [comment]
Thank you, will try this out and see if there are issues.

**Comment by rhlsthrm** [comment]
https://github.com/connext/nxtp/pull/231

Seems like we might not need that anymore. Fixed here.

**Comment by alfredolopez80** [comment]
Excellent all is ready in this part
