### ISSUE TITLE
[EXPLORER] Token filters not working

### ISSUE THREAD

**Issue by Tommy-R8** [connext/nxtp#2316]
**Describe the bug**
When looking at an address, the asset filters don't do anything.

**To Reproduce**
1. Go to an address on Connextscan
2. Click on Asset selector button
3. Select an Asset

**Expected behavior**
Right now my address has only TEST transfers. When I click on ETH, it should show me an empty list.

**Screenshots**
![image](https://user-images.githubusercontent.com/84744304/199575992-9fdb02dc-878f-4a5c-84b0-943650bcf59c.png)

**Comment by alexwhte** [comment]
Linking as something to test on mainnet pre-launch
