### ISSUE TITLE
Add a scroll bar for Desktop

### ISSUE THREAD

**Issue by 0xanedi** [connext/nxtp#2329]
## Problem
Users without a mouse, a with a broken scroll wheel or without reliable track pads with gestures can't scroll because of a lack of scroll bar on site. This has only been seen in Chromium-based browsers.

## Proposed Solution
- Implement a discrete scrollbar on the right. Just use Chrome's default for now and then maybe something like toher sites that are sleeker and thinner (occupying less space).

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] I can scroll successfully without using a mousewheel

**Comment by alexwhte** [comment]
@0xanedi Thanks for this feedback

**Comment by alexwhte** [comment]
added to coinhippo backlog

**Comment by Tommy-R8** [comment]
I think scrollbar was added but now when using the faucet dropdown 2 scrollbars appear 
![image](https://user-images.githubusercontent.com/84744304/200147943-8344d7d9-4688-4a4a-8058-18f2c966aad6.png)

**Comment by Tommy-R8** [comment]
Also it seems that the scrollbar is still active and scrolls over the background while having other modals popped up (like chain or token selection)

**Comment by alexwhte** [comment]
Couple feedbacks ([Hop](https://app.hop.exchange/#/send?token=ETH) does a good job of the below) 
1. Scrollbar should only appear when the UI needs to scroll. 
2. As Tommy said, the bar has an extra padding for some reason 
![image](https://user-images.githubusercontent.com/37959170/200462995-66f4033e-547d-4e49-b38d-87e60273f510.png)
