### ISSUE TITLE
As a [end user] I want see a timer/counter in order to estimate how long it's going to take

### ISSUE THREAD

**Issue by 0xanedi** [connext/nxtp#2338]
## Problem
_Time uncertainty while bridging._ 

## Proposed Solution
_Implement a time estimator for transaction. [my comment] I understand that this may be completely impossible to implement reliably on all chains_

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] I can get correct estimations on how long it is going to take me to bridge my assets

**Comment by alexwhte** [comment]
Working on figuuring this out this week
