### ISSUE TITLE
As a [end user], I like a tooltip that explains why destination chain gas fees are important

### ISSUE THREAD

**Issue by 0xanedi** [connext/nxtp#2339]
## Problem
_Users are reading the destination chain gas fee status and interpreting they will need to pay actual gas in destionation to claim._ 

## Proposed Solution
_Create a tooltip that more or less says "Gas fees on destination chain are important to estimate the Router Gas Fees, paid in the bridged assets."_
- [ ] Maybe clarify that users DON'T NEED gas on destination

## Acceptance Criteria
_From a user perspective, the below criteria must be met to consider this done:_
- [ ] I can understand all the fees I will be paying throughout the whole process and that I will only have to interact on the sender chain side of things.

**Comment by alexwhte** [comment]
Youve seen our current tooltip? This is more wording? or you havent yet

![image](https://user-images.githubusercontent.com/37959170/199854499-5d4873f9-79d4-425f-b6af-0481ae29cdde.png)

**Comment by 0xanedi** [comment]
> Youve seen our current tooltip? This is more wording? or you havent yet
> 
> ![image](https://user-images.githubusercontent.com/37959170/199854499-5d4873f9-79d4-425f-b6af-0481ae29cdde.png)

@alexwhte The user that proposed this said a tooltip should be added above the Gwei amount on the destination chain, clarifying that users don't need to worry about gas on the destination chain. Lmk if this is useful

Also, I think the tooltip you're showing is good and you should leave it as is.
