### ISSUE TITLE
Gas Fee field glitching

### ISSUE THREAD

**Issue by Tommy-R8** [connext/nxtp#2347]
**Describe the bug**

**To Reproduce**
1. Go to https://amarok-testnet.coinhippo.io/
2. Input a valid amount
3. Open the fee breakdown
4. Switch destination chain
5. See error (asset doesn't correspond to destination chain and/or glitches)

**Expected behavior**
The gas fee should be expressed correctly in the native token of the destination chain, and should change accordingly when switching destination.

**Screenshots**
https://discord.com/channels/454734546869551114/1037458565503389877/1037710795271852062

**Comment by alexwhte** [comment]
fixed https://discord.com/channels/454734546869551114/909827059373723648/1037860013907116133
