### ISSUE TITLE
Slippage setting allows invalid numbers

### ISSUE THREAD

**Issue by Tommy-R8** [connext/nxtp#2348]
**Describe the bug**
When filling the slippage field, it only accepts values between 0 and 100 (correctly). However, if the user sets a value outside of this range and then changes the "Infinite approval" toggle to the off position, the "Apply" button becomes available to click on and save changes.

**To Reproduce**
1. Go to https://amarok-testnet.coinhippo.io/
2. Click on Settings
3. Set slippage to a value higher than 100
4. Turn off infinite approval
5. See error

**Expected behavior**
The "Apply" button should never become available with an invalid slippage tolerance number.
Give an error message when the value is invalid.
Have warnings for too low/high slippage.

**Screenshots**
https://discord.com/channels/454734546869551114/1037575162637320222/1037581803747291137
![image](https://user-images.githubusercontent.com/84744304/199895583-6745db90-be29-45b6-a2de-d8f9f9ead5c2.png)
![image](https://user-images.githubusercontent.com/84744304/199895598-84e46ac2-3761-46ff-bc6a-4da7fe1f9e7b.png)

**Comment by alexwhte** [comment]
fixed in new ui

![image](https://user-images.githubusercontent.com/37959170/200146286-682f7257-b639-4882-8384-d2dce2b6e5cf.png)
