### ISSUE TITLE
Chain reverse button glitching

### ISSUE THREAD

**Issue by Tommy-R8** [connext/nxtp#2349]
**Describe the bug**
When clicking on the button to reverse the chain order (origin - destination), it doesn't change anything and it visually glitches.

**To Reproduce**
1. Go to https://amarok-testnet.coinhippo.io/
2. Click on the reverse button (with wallet connected to one of the chains)
3. See error

**Expected behavior**
The button should switch the origin chain and the destination chain, and do so without giving any visual errors.

**Screenshots**
https://discord.com/channels/454734546869551114/1037945836451151962/1037948557870768138

**Comment by pjenviri** [comment]
fixed
