### ISSUE TITLE
Chain search bar bug

### ISSUE THREAD

**Issue by Tommy-R8** [connext/nxtp#2361]
**Describe the bug**
Search bar on chain selection seems to throw random results or not filter correctly at all

**To Reproduce**
1. Go to https://amarok-testnet.coinhippo.io/
2. Click on the chain selector
3. Start typing

**Expected behavior**
Search bar should filter correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/84744304/200147640-2cdb498c-7adb-45d6-b8c9-8b6cc0a4cf94.png)
![image](https://user-images.githubusercontent.com/84744304/200147644-17b77c9f-fe49-4b35-8bc1-693d4b3bf40b.png)

**Comment by alexwhte** [comment]
Confirmed this is still an issue, filtering works fine after I type the second letter though. It's after hte first letter that I see no results.
