### ISSUE TITLE
Address copy to clipboard button doesn't work when displaying ENS domain

### ISSUE THREAD

**Issue by Tommy-R8** [connext/nxtp#2367]
**Describe the bug**
When connected with a wallet that has an ENS domain resolving to it, the button to copy the address on the top bar copies the ENS domain instead of the full address.

**To Reproduce**
1. Go to https://amarok-testnet.coinhippo.io/
2. Connect an address with an ENS domain resolving to it
3. Click on the clipboard button

**Expected behavior**
The button should always copy the full 0x address.

**Screenshots**
![image](https://user-images.githubusercontent.com/84744304/200186246-cecb821d-3b6d-446a-81e3-2f08bee97764.png)

**Comment by alexwhte** [comment]
works for me now closing
