### ISSUE TITLE
[EXPLORER] As a [end user], I want to see the final gas cost of transactions

### ISSUE THREAD

**Issue by Tommy-R8** [connext/nxtp#2369]
## Problem
Currently, the explorer shows gas limit and gas price, but doesn't show gas cost. That leaves the total gas cost to be calculated by the user.

## Proposed Solution
Add a new field that shows the total gas cost of the transaction.

## Acceptance Criteria
Self explanatory

**Comment by alexwhte** [comment]
What is gas limit? 
We are showing Destination Gas Fee
We could alert user if gas is high >X per chain,but leaving origin gas out intentionally for now as it's redundante to wallet
