### ISSUE TITLE
Fuse Subgraph Issues

### ISSUE THREAD

**Issue by Tommy-R8** [connext/nxtp#2404]
**Describe the bug**
Router logs (p2p, nodehodler) for an auction from Fuse to any other chain say that the Fuse subgraph is out of sync. Previously, the status page on connextscan showed both the RPC and the subgraph latest blocks as being 0, as if they were missing. Now they show the correct block numbers and the chain looks like it's synced, but the routers are still giving an error.

**To Reproduce**
1. Go to https://bridge.connext.network/
2. Select Fuse as origin chain
3. Select BNB Chain/Polygon as destination chain
4. Get no bids
5. Search for transaction ID in logdna
6. Filter by the two routers that support Fuse
7. See error

**Expected behavior**
Subgraph should be synced.

**Comment by alexwhte** [comment]
We are deprecating fuse
