### ISSUE TITLE
Unable to add liquidity to routers on mainnet

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#2408]
**Describe the bug**
A clear and concise description of what the bug is. Adding liquiddity to a router fails
1. The router IDs dont line up
![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/0657a545-6638-462d-a0b8-34893c09c191)
![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/85b71c69-f00b-444d-bb73-2b7f1ceea978)

2. We see this error 
`cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x3A40064c2B0004ab594F44c24D29dF1943108C73","to":"0x683151d43758BB7A37e9d47386154d5Ae9b8AC48","data":"0x2d3f9ef60000000000000000000000000000000000000000000000000000000000989680000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000071dd9fc6fe5427f0c7cd7d42bc89effe11c6d4b7","accessList":null}, error={"code":-32603,"message":"execution reverted","data":{"originalError":{"code":3,"data":"0xa32632f8","message":"execution reverted"}}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)`

**To Reproduce**
1. Go to https://d3f1g7sq6u4698.cloudfront.net/routers
2. Click on router
3. Click manage router
4. Add liquiditiy

.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/f16861db-3fb1-4c2c-b1c9-3fd88ec1ecfb)

**Comment by just-a-node** [comment]
Add liq working now: https://etherscan.io/tx/0x477987f4e3ee936b5c5438aaea45341c63b2023d69b80f10342782cef562d1dc
