### ISSUE TITLE
Fetch relayer fee on mainnet 

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#2458]
## Problem
Currently destination gas fee (relayer fee) is showing 0 on mainnet UI

## Proposed Solution
- SDK method to fetch this
- Add to UI 

## Acceptance Criteria
- [x] Able to call relayer fee
- [x] Destination Gas Fee in UI is hooked into this and fetching correctly
- [ ] Estimated Received amount includes this fee

**Comment by just-a-node** [comment]
"Estimated Received amount includes this fee" - estimated received is in a different asset than the native gas fee, believe this should not be included
