### ISSUE TITLE
Receive local not working in the UI mainnet

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#2459]
**Describe the bug**
Receive local does not seem to be in our SDK since interface changes
This transaction was supposed to receive nextUSDC
https://amarok.connextscan.io/tx/0xebaccb5c83d9c7f464dea3e9c819fd6611f36c4c0f26223e3054b1da02215967 
https://polygonscan.com/tx/0x22e410674aebaa419375c82d77c9712144e8a339b70d27518a0121087215c829

Current workaroundd (not working)
https://discord.com/channels/454734546869551114/909827059373723648/1040688562166845440

**To Reproduce**
1. Go to Bridge andd toggle 'Receive NextAsset'
2. Send USDC from mainnt to spoke
3. Only receive USDC

**Expected behavior**
This works in the UI
https://docs.connext.network/developers/reference/contracts/calls#xcallintolocal

**Version:**

**Additional context**

**Screenshots**

**Comment by just-a-node** [comment]
Open until UI updated with SDK changes.
