### ISSUE TITLE
Arbitrum Nova subgraph issues

### ISSUE THREAD

**Issue by Tommy-R8** [connext/nxtp#2487]
**Describe the bug**
The Arbitrum Nova subgraph appears to be unreachable or missing. This (I believe) causes a "Not enough bridge liquidity to complete transfer. Use a smaller amount." error to appear when trying to transfer TO Arbitrum Nova.

**To Reproduce**
1. Go to https://bridge.connext.network/
2. Select destination chain Arbitrum Nova
3. Select origin chain BNB/Arbitrum/Optimism/Polygon (all of these are supported by the router with USDC liquidity)
4. Choose an amount like 100 USDC
5. See error (the estimated received will appear because a bid was received, but the site will still show not enough liquidity)

**Expected behavior**
The Arbitrum Nova subgraph should work correctly.

**Additional context**
It seems that after some time the subgraph loaded, and now the error doesn't show up and the subgraph data appears correctly in the status page of the explorer. This may be a temporary/intermittent issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/84744304/201952458-a88a7db7-e671-4689-8b24-7f1072e20db5.png)
![image](https://user-images.githubusercontent.com/84744304/201953120-bf49653c-6e8d-47f9-b74d-763a34851dae.png)

**Comment by rhlsthrm** [comment]
This is temporary/intermittent, unfortunately won't fix this.
