### ISSUE TITLE
Create watcher adapter

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#2627]
Watcher adapter will be an adapter package. The idea is that the adapter package can be used in a standalone watcher agent, or it can be implemented into any workload.

Definition of done:
- [ ] Package exists and is able to be imported into other packages.
- [ ] Function to get total locked amount for a given asset.
- [ ] Function to get total minted amount for a given asset.
- [ ] Wrapper function to validate all assets and make sure that locked >= minted at all times and return info indicating it needs to be paused.

**Comment by jakekidd** [comment]
Opened PR draft https://github.com/connext/nxtp/pull/2638
