### ISSUE TITLE
Price impact tooltip feedback

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#2640]
## Background

Tooltip says "The pools is currently overweighted in nextWETH. Providing WETH instead will give you positive price impact and bonus LP tokens." even when providing liquidity in both assets.

a) change "pools" to singular "pool"
b) change "Providing WETH instead will..." to "Providing more WETH will..."

![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/505b3458-a553-44ea-88ab-bf4a2e315d42)

**Comment by just-a-node** [comment]
Another fix: negative price impact actually means bonus LP tokens, so the tooltip should appear when price impact is *positive*, like here.

<img width="363" alt="image" src="https://user-images.githubusercontent.com/16638982/204734607-dd2b068d-2dc3-4616-91db-9b37c29aa370.png">

Let's also change the tooltip language to just mention bonus LP tokens. 

Current:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/16638982/204735284-9b3f581c-adbd-40b1-a0a8-5834ebd1aedf.png">

New:

If pool is overweighted in Asset:
```
The pool is currently overweighted in <Asset>. Providing more <nextAsset> will grant bonus LP tokens.
  Convert to nextAsset
  Using Bridge | Using AMM
```

If pool is overweighted in nextAsset:
```
The pool is currently overweighted in <nextAsset>. Providing more <Asset> will grant bonus LP tokens.
  Convert to Asset
  Using Bridge | Using AMM
```

**Comment by alexwhte** [comment]
Last fix. Please change to the below where price impact is POSITIVE
- The 'Get nextUSDC' button automatically goes to the Bridge UI with preset settings for bootstrapping 
- 
<img width="398" alt="image" src="https://user-images.githubusercontent.com/37959170/207718853-6ca08bbc-8537-422b-8f4e-d98382c2b817.png">

**Comment by just-a-node** [comment]
One more case to handle:

When price impact is **positive** when providing **nextAsset**: tooltip should say "The pool is currently overweighted in <nextAsset>. Providing more <Asset> may result in bonus LP tokens!" and do NOT show the "Get <Asset>" button.

Currently, it shows the same prompt to get nextAsset when price impact is positive, regardless of which asset is actually overweight.
![image](https://user-images.githubusercontent.com/16638982/208487762-52cc594d-cbb1-454f-8296-68de9e1ed61a.png)
