### ISSUE TITLE
As a user I want to send 0 value fast path transfers 

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#2651]
## Problem
Devs want lower latency transfers with 0-value calldata

## Proposed Solution
Enable unauthenticated calls with 0 value and 0 address

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] Dev can send an unauthenticated transfer with no value and no address

**Comment by wanglonghong** [comment]
it has been fixed
