### ISSUE TITLE
Swap should show "nextAsset" name correctly

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#2663]
**Describe the bug**
In the swap UI, the "nextAsset" is not displayed correctly.

One of the assets should be "WETH" and one should be "nextWETH"
![image](https://user-images.githubusercontent.com/16638982/205995957-38698809-949f-4b46-ae10-f61a7e67cbe1.png)

![image](https://user-images.githubusercontent.com/16638982/205996015-6ddddb11-b525-4e3c-ae2d-a237f9b9bfcb.png)

**Comment by pjenviri** [comment]
The contract of WETH is https://goerli-optimism.etherscan.io/token/0x74c6FD7D2Bc6a8F0Ebd7D78321A95471b8C2B806, while the nextWETH contract address is https://goerli-optimism.etherscan.io/token/0x39B061B7e41DE8B721f9aEcEB6b3f17ECB7ba63E.

but  the `getPool` returns an array of symbols indicating that
- WETH: https://goerli-optimism.etherscan.io/token/0x39B061B7e41DE8B721f9aEcEB6b3f17ECB7ba63E
- nextWETH: https://goerli-optimism.etherscan.io/token/0x74c6FD7D2Bc6a8F0Ebd7D78321A95471b8C2B806

<img width="1079" alt="getPool" src="https://user-images.githubusercontent.com/87146398/207234085-478ee135-a612-47b1-80e0-95b762462ebf.png">

I think it needs to be swapped.

**Comment by just-a-node** [comment]
`getPool` returns the assets in the index positions in which they were registered. So, for example, the nextAsset is not always index 0. 

`getPool` also now contains `tokenIndices` property per pool, which is a `Map<string, number>` that acts as a lookup for the asset address => index position.
