### ISSUE TITLE
In the swap UI, a better error message should be displayed when slippage is exceeded

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#2664]
## Problem

Show better error message when slippage is exceeded.

![image](https://user-images.githubusercontent.com/16638982/205996557-d9a1714e-b79a-4523-a21e-7362598d4582.png)

**Comment by pjenviri** [comment]
Can you suggest the message to show on the UI? and how to check that the error is from the exceeded slippage?

**Comment by alexwhte** [comment]
@PJ whenever this error is thrown can we please show this message? 

> Slippage exceeded. Please try increasing slippage tolerance and resubmitting your transfer.

**Comment by pjenviri** [comment]
@alexwhte thanks. we have adjusted the UI to show the above message.
