### ISSUE TITLE
Latest Transfers list not refreshing when changing connected wallet

### ISSUE THREAD

**Issue by Tommy-R8** [connext/nxtp#2670]
**Describe the bug**
When a user is connected to the site with a wallet, they are able to see the latest transfers of that address. When the user switches the wallet to a different one, the latest transfers still show those of the previously connected address.

**To Reproduce**
1. Go to https://amarok-testnet.coinhippo.io/
2. Connect an address and open the Latest Transfers list
3. Switch addresses in Metamask

**Expected behavior**
The latest transfers list should refresh when the connected address changes.

**Comment by alexwhte** [comment]
@Tommy-R8 I'm unable to replicate, is this fixed? Can we move to done?

**Comment by alexwhte** [comment]
tested again and closing
