### ISSUE TITLE
Too many rpc calls, running into rate limiting

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#2710]
## Problem

UI is sending too many RPC calls (i.e. Ankr is rate limiting and 429'ing the requests). 

## Proposed Solution

See if we can minimize rpc calls through batching, caching, or spreading load between different providers.

**Comment by pjenviri** [comment]
We have already cached it, but IMO it doesn't help much, as users can reopen their browsers anytime. Btw, are you using `JsonRpcProvider`? Maybe worth to change to `StaticJsonRpcProvider`?  We also see a lot of RPC requests when calling `getYieldData`.
