### ISSUE TITLE
Received asset should show the correct one

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#2724]
**Describe the bug**
User receives USDC but transfer status shows nextUSDC received.

![image](https://user-images.githubusercontent.com/16638982/207705750-b73276b2-2242-43b0-8934-b58f0a5fe24c.png)

![image](https://user-images.githubusercontent.com/16638982/207705792-f0ab0813-4b01-46be-afd1-afbf3a6458e5.png)

**Expected behavior**
Should show the correct asset being received.

**Comment by pjenviri** [comment]
We use the data from the field: `destination_transacting_asset` or `destination_local_asset`. Here's the retrieved data:
<img width="654" alt="data" src="https://user-images.githubusercontent.com/87146398/208049485-080a399b-2ef1-4712-b1e3-2b80d2df27ec.png">

**Comment by just-a-node** [comment]
Receiving side should always show `destination_transacting_amount`, looking into why these are returning `null`.
