### ISSUE TITLE
Origin sent amount should show the value before slippage

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#2725]
**Describe the bug**
User sends 40 USDC but transfer status shows $39.**

![image](https://user-images.githubusercontent.com/16638982/207705956-dba12085-9970-4fa0-bf37-e80d3bd2c734.png)

**Expected behavior**
Should show the correct sent amount *before slippage*.

The actual amount received should also be updated with the final received value (*not* the estimated amount).

**Comment by pjenviri** [comment]
We display the data received from fields: `origin_bridged_amount` and `origin_transacting_amount.`

**Comment by just-a-node** [comment]
This is showing `origin_bridged_amount`, we should show `origin_transacting_amount` always for origin amount.

**Comment by pjenviri** [comment]
fixed

**Comment by just-a-node** [comment]
Reopening this because the wrong value is shown in the sidebar transaction still.

![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/0346c530-81cc-4c12-95e8-c87b496eb47a)

However, it's correct when opened in the explorer:

![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/789b5d36-d6b1-44f9-954e-cb9ab9ff5f63)

**Comment by alexwhte** [comment]
@just-a-node Please close if you feel it's gtg
I believe this was fixed in https://github.com/connext/nxtp/issues/2837 as well
