### ISSUE TITLE
Show volume and transfers data on routers page

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#2728]
## Problem

Routers pages should show the volume and transfers.

![image](https://user-images.githubusercontent.com/16638982/207706717-614e73d5-eae3-4f1e-8e17-7375672c5928.png)
![image](https://user-images.githubusercontent.com/16638982/207706751-26071882-3359-4447-8726-52f281889ccb.png)

**Comment by pjenviri** [comment]
Similar to https://github.com/connext/nxtp/issues/2729, we cannot get the data from 
- https://postgrest.mainnet.connext.ninja/daily_transfer_metrics
- https://postgrest.mainnet.connext.ninja/daily_transfer_volume

<img width="526" alt="Screenshot 2565-12-16 at 14 44 37" src="https://user-images.githubusercontent.com/87146398/208048952-6b6d4955-8fc3-4c43-81fd-9d1b92962495.png">
<img width="532" alt="Screenshot 2565-12-16 at 14 44 28" src="https://user-images.githubusercontent.com/87146398/208048955-1bc4cfe0-635d-4ca5-8ccc-b6a7bbc3a694.png">

**Comment by just-a-node** [comment]
This should be working now
