### ISSUE TITLE
Overview page should show volume and transfers data

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#2729]
## Problem

Overview page needs to show volume and transfers data.

![image](https://user-images.githubusercontent.com/16638982/207706902-8b7bb2ff-e055-43ec-8289-c851394c36d7.png)

**Comment by pjenviri** [comment]
it's because we're getting errors when calling:
- https://postgrest.mainnet.connext.ninja/daily_transfer_metrics
- https://postgrest.mainnet.connext.ninja/daily_transfer_volume

**Comment by just-a-node** [comment]
This should be working now
