### ISSUE TITLE
Optimism USDC pool sending undefined symbol to pricefeed

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#2730]
**Describe the bug**

Optimism USDC pool is not loading, sending `undefined` token symbol to `getLiquidityMiningAprPerPool`.

https://d1h9h37hgxfzvk.cloudfront.net/pool/USDC-on-optimism

**Comment by pjenviri** [comment]
Always get this error. Could you check?
<img width="990" alt="er" src="https://user-images.githubusercontent.com/87146398/208045622-7ebc63d5-fd95-4626-b536-6ac1ce097bfa.png">

**Comment by just-a-node** [comment]
We'll be releasing beta.17 today which should resolve this!

**Comment by alexwhte** [comment]
is this the same issue? 
<img width="418" alt="image" src="https://user-images.githubusercontent.com/37959170/208965191-42ae226a-b104-43e8-804f-4dc8b54f409a.png">

**Comment by LayneHaber** [comment]
<img width="635" alt="Screenshot 2022-12-21 at 6 21 52 PM" src="https://user-images.githubusercontent.com/12769011/209034243-f1cc1fab-3b62-4b3f-9160-03ce5f245e66.png">

could this be a config issue? when i pull up the above link, i see `symbol` is `undefined` (which is then passed onto the coinbase url and errors). the `symbol` value seems to [come directly from the config](https://github.com/CoinHippo-Labs/connext-bridge/blob/d81a98c41e5bc9e11eabf00b5beab3bcd099bfd2/components/navbar/index.js#L979-L992)

**Comment by pjenviri** [comment]
It's because we couldn't get data at that time. It looks like it's working now, though.
