### ISSUE TITLE
Token cutoff on large amounts in My Positions

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#2731]
**Describe the bug**

In My Positions, the Pool Tokens and Share values are overflowing. There should be a cut-off.

![image](https://user-images.githubusercontent.com/16638982/207720904-a896e8b0-3faf-4c45-8cb9-c998845489e0.png)

**Comment by pjenviri** [comment]
We think it's because; USDC decimal is 6, but the decimal of the lpTokenBalance returned from `getUserPools` is 18. Can you please verify?

**Comment by just-a-node** [comment]
That is correct - LP tokens have 18 decimals.
