### ISSUE TITLE
Insufficient balance when balance is sufficient

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#2757]
**Describe the bug**

Getting the "insufficent balance" error occasionally when balance is clearly sufficient. Not sure what threshold causes it, it's happening on and off.

![image](https://user-images.githubusercontent.com/16638982/208156078-ec4fe3df-7ff7-49b8-bae8-9fc430ee8904.png)

**Comment by alexwhte** [comment]
Im also seeing this error first
"missing revert data in call exception; Transaction reverted without a reason string"
<img width="547" alt="image" src="https://user-images.githubusercontent.com/37959170/208973562-b9f2272d-af35-4af4-9533-ee116af72fe5.png">

then "INsufficient balance"
<img width="504" alt="image" src="https://user-images.githubusercontent.com/37959170/208973609-564892f7-a267-4d63-9bcd-0104d5ba871a.png">

**Comment by just-a-node** [comment]
It's like this on mainnet for me:

![image](https://user-images.githubusercontent.com/16638982/209031392-573be8b1-51f7-43f2-885a-3d31a8e9e2c1.png)

Can't seem to reproduce on testnet prod/staging. Might be something to do with USDC specifically due to decimals

**Comment by pjenviri** [comment]
I couldn't reproduce it on mainnet. Are you guys still seeing the issue?

**Comment by pjenviri** [comment]
I didn't see the `Insufficient fee` error message, but I got the`call revert exception ...`. It's the response of the `calculatedAmountReceived`. Can you please verify my input? 
<img width="1440" alt="Screen Shot 2565-12-23 at 00 47 17" src="https://user-images.githubusercontent.com/87146398/209198567-e5434e24-6543-4117-87c6-1333e1816424.png">

**Comment by alexwhte** [comment]
Same error cc @just-a-node https://github.com/connext/nxtp/issues/2824
