### ISSUE TITLE
Testnet Optimism Pool: Cannot read properties of undefined (reading 'balances')

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#2784]
https://testnet.bridge.connext.network/pool/ETH-on-optimism

![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/6631fe6e-2be6-4dd8-8c9b-6d5895dc00df)Any information that gives more context as to why this task exists, and why it matters. This might include: links to discussions, documentation, or other Jira issues / tasks

**Comment by alexwhte** [comment]
@just-a-node are these dupes? https://github.com/connext/nxtp/issues/2730

**Comment by alexwhte** [comment]
Now getting this issue 

missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"to":"0x5Ea1bb242326044699C3d81341c5f535d5Af1504","data":"0xad94911b292e02936c5b0f88fab7f755caac58d92cd10b13f484cd46f6dd45468cb23e3f00000000000000000000000039b061b7e41de8b721f9aeceb6b3f17ecb7ba63e","accessList":null}, error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":68,\"error\":{\"code\":-32000,\"message\":\"execution reverted\"}}","error":{"code":-32000},"requestBody":"{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x5ea1bb242326044699c3d81341c5f535d5af1504\",\"data\":\"0xad94911b292e02936c5b0f88fab7f755caac58d92cd10b13f484cd46f6dd45468cb23e3f00000000000000000000000039b061b7e41de8b721f9aeceb6b3f17ecb7ba63e\"},\"latest\"],\"id\":68,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://rpc.ankr.com/optimism_testnet"}, code=CALL_EXCEPTION, version=providers/5.7.2)

![image](https://user-images.githubusercontent.com/37959170/208972063-3a986465-6ccb-4f7c-a971-abc4f3542b0e.png)

**Comment by LayneHaber** [comment]
> @just-a-node are these dupes? #2730

i dont think so as these seem to originate at different functions

**Comment by LayneHaber** [comment]
im not seeing this error anymore on the link you posted
