### ISSUE TITLE
USDC decimals incorrect

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#2797]
## Background

Transfers for USDC are showing wrong decimals. 

Correct decimals are captured in the object returned by `getPool`. Note that all LP tokens will be 18 decimals.

![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/e180fd8e-b5b0-4ff4-9b10-32b69a47e07c)

![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/f1720084-080a-44cf-a05f-532f30877073)

**Comment by LayneHaber** [comment]
duplicate of #2815
