### ISSUE TITLE
My Pools section is showing all pools even though I have no balance

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#2804]
In mainnet https://d1h9h37hgxfzvk.cloudfront.net/pools

![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/943f696e-ea24-4f46-aec2-17daa597fbb1)

**Comment by just-a-node** [comment]
Pools with 0% share are still showing up in "My Pools" section.
