### ISSUE TITLE
Unable to withdraw liquidity

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#2805]
**Describe the bug**
Withdrawing liquidity is not working for multiple reasons. See 
https://www.awesomescreenshot.com/video/13471955?key=06aebc9110b32964d90b4c80fba0a454

1. Clicking the % button shortcuts doesnt do anything 
2. Typing in a number small enough (less than my amount pooled) works but doesnt allow me to 'Remove Liquidity', as the button is still unavailable
3. Typing in a number more than the liquidity I have throws this error 
> call revert exception; VM Exception while processing transaction: reverted with reason string "exceed total supply" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="calculateRemoveSwapLiquidity(bytes32,uint256)", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001365786365656420746f74616c20737570706c7900000000000000000000000000", errorArgs=["exceed total supply"], errorName="Error", errorSignature="Error(string)", reason="exceed total supply", code=CALL_EXCEPTION, version=abi/5.7.0)

**Comment by pjenviri** [comment]
We've fixed all the above issues. I was able to add and withdraw liquidity. Please try.

**Comment by alexwhte** [comment]
I'm getting this error on BSC. Is it due to https://github.com/connext/nxtp/issues/2814 ? 

<img width="457" alt="image" src="https://user-images.githubusercontent.com/37959170/209366742-0b5deb0c-55a9-420c-be19-7a83e146aafd.png">

**Comment by just-a-node** [comment]
Due to #2859
