### ISSUE TITLE
Invalid BigNumber value on bridge input

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#2814]
**Describe the bug**

BigNumber value on bridge input:
![image](https://user-images.githubusercontent.com/16638982/209170194-8d8a79eb-34ef-4fcd-abcb-041997ce808c.png)

Call revert:
![image](https://user-images.githubusercontent.com/16638982/209171498-38176499-6dfc-4af5-93d6-6ec81598ebe5.png)

**Comment by pjenviri** [comment]
Similar to https://github.com/connext/nxtp/issues/2757, It's the response of the `calculatedAmountReceived`. Can you please verify my input?
<img width="1440" alt="Screen Shot 2565-12-23 at 01 04 44" src="https://user-images.githubusercontent.com/87146398/209199158-e2d0454b-ed0a-4543-bb6c-99aceb6086de.png">

**Comment by just-a-node** [comment]
See https://github.com/connext/nxtp/issues/2824
