### ISSUE TITLE
USDC decimals are off

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#2815]
**Describe the bug**

![image](https://user-images.githubusercontent.com/16638982/209170489-d6e3f677-8d0d-4dc3-a8f0-ea02a51dde94.png)

This affecting total volume too:

![image](https://user-images.githubusercontent.com/16638982/209170573-ddf2f7a3-e32c-46c7-9ce5-cb5b839426e6.png)

**Comment by LayneHaber** [comment]
see also #2833

**Comment by LayneHaber** [comment]
see also https://github.com/connext/nxtp/issues/2797

**Comment by LayneHaber** [comment]
also apparent in tiles:

![image](https://user-images.githubusercontent.com/12769011/209242790-9d06423b-393b-465f-b5de-40ae6dfd4a7f.png)

**Comment by alexwhte** [comment]
Still seeing this error on the tiles for Lateest Transfers

**Comment by LayneHaber** [comment]
another one, this is blocking mainnet -> gnosis

![image](https://user-images.githubusercontent.com/12769011/209394453-c72e8540-260a-486a-8519-3367937bebdd.png)

**Comment by alexwhte** [comment]
@nrsirapop  Can you please look into this one again? A router flagged it yesterday 

https://discord.com/channels/454734546869551114/922461791617957898/1057622563062292560

**Comment by alexwhte** [comment]
also here https://discord.com/channels/454734546869551114/922461791617957898/1057626139625017396

**Comment by pjenviri** [comment]
It works for me.![usdc decimal.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/a1b02ab6-c55c-483b-b97a-3fdedddf137f) 
![usdc_decimal.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/70e8e50a-d81b-4973-9dbc-028e9f8994fd)
