### ISSUE TITLE
Swap error handling changes for "Amount cannot be less than or equal to 0"

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#2820]
**Describe the bug**
See about 45 seconds in we are showing this error "Amount cannot be less than or equal to 0" where it's not a user error yet
https://www.awesomescreenshot.com/video/13491988?key=84e41fec337630534b3f87e4b181f805

Instead of this error, we should just disable the ability to click the action button "Swap". After they enter an amount, it is available. We dont need as harsh of an error because it assumes the user is trying to swap before they may be ready. 

In these cases:
1. User enters 1, then deletes it, error is shown
2. User switches to Gnosis chain, error is shown

**Comment by just-a-node** [comment]
Still seeing the error when switching balance from 1 -> 0. The request here is to disable/grey out the "Swap" button until the user inputs something > 0 *instead* of showing the error "The amount cannot be equal to or less than 0."
