### ISSUE TITLE
Swapping broken on Gnosis chain

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#2822]
**Describe the bug**
Getting an error on Gnosis
missing revert data in call exception; Transaction reverted without a reason string

https://www.awesomescreenshot.com/video/13492116?key=b49806b1d806f6c9575f76a71b9ef463

**To Reproduce**
1. Go to https://d1h9h37hgxfzvk.cloudfront.net/swap/USDC-on-gnosis?amount=1&from=USDC
2. Enter an amount

**Comment by alexwhte** [comment]
@just-a-node @nrsirapop Is this fixed? Router just flagged it on mainnet 

https://discord.com/channels/454734546869551114/922461791617957898/1057623904442646558

**Comment by pjenviri** [comment]
It works for me. Please check it again on your end![amount.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/a318da81-2231-4419-a1ab-b79e44cb3ffd).

**Comment by rhlsthrm** [comment]
Confirmed working.
