### ISSUE TITLE
Receive amount displays weird value

### ISSUE THREAD

**Issue by LayneHaber** [connext/nxtp#2837]
**Describe the bug**
Receive amount is off, looks close to the pool balance?

**To Reproduce**
1. Try to swap USDC

**Additional context**
See screenshots:

![image](https://user-images.githubusercontent.com/12769011/209242939-db6118f5-92c7-4c35-a32e-bfb686f78c7b.png)

![image](https://user-images.githubusercontent.com/12769011/209242953-6f0df3b2-24b1-4eac-a780-d71fe9f1e592.png)

**Comment by just-a-node** [comment]
This should be "bridge" USDC based on screenshots. Testing on my side is working for all routes - will wait for Layne to check before closing out.

**Comment by alexwhte** [comment]
Is this a separate issue? @just-a-node Think the UI is subtracting fees from the origin amount (not pulling the actual) 
That's more interesting. I completed a transfer of 7 USDC from Polygon to BSC - https://amarok.connextscan.io/tx/0x1955e4e24943899a14510e69e5cca8ea07d4b2927dfc0166a2815c3c9d2ccb93 and it shows 6.9965
nextUSDC is receved. BUT, if we look in BSC scan - https://bscscan.com/tx/0x5948bd7fa520b6b5ce37bf412a5ca68c95bf3ddd6d718ddc81ac0961fb57a874 - it shows 7.018063 is received - that's what I see in my wallet! How? 

Having said that, I dont totally understand how the user could receive more nextUSDC

**Comment by pjenviri** [comment]
It is because the value of `destination_transaction_amount` is `null`.
