### ISSUE TITLE
Mislabeled received asset in explorer

### ISSUE THREAD

**Issue by LayneHaber** [connext/nxtp#2841]
**Describe the bug**
Bug labels `WETH` received as `nextWETH` in explorer in slow mode

**To Reproduce**
1. Transfer WETH
2. Wait for transfer to be `received`
3. Find transfer on explorer

**Additional context**
Example transfer in connextscan [here](https://amarok.connextscan.io/tx/0x52e6ad088cf144a3dcc08f4c4dd8825c018cede88b1d962802aa32aaa27da48d) (shows `nextWETH` received), and corresponding block explorer link showing assets transferred [here](https://gnosisscan.io/tx/0x916394e6137eb110605913389b5838ff6fb6457333411c53fc9f43946936d026)

**Comment by pjenviri** [comment]
It's probably because the `destination_transacting_asset` (returned by the SDK) is `null`. 
![Screenshot_2565-12-24_at_11.35.46.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/ce2806e4-8d39-4e5a-bd61-20c5c0a4e1bb)

**Comment by rhlsthrm** [comment]
> It's probably because the `destination_transacting_asset` (returned by the SDK) is `null`. ![Screenshot_2565-12-24_at_11.35.46.png](https://camo.githubusercontent.com/41eb3f185a333188cc4b3564db4da8f73bd48993853a2a803933e3dfb7b39bc7/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632316533623736376231623638363433303631323735642f63653238303665342d386433392d346535612d626436312d323063356330613465316262)

This is fixed now!
