### ISSUE TITLE
Pooling USDC issues 

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#2856]
**Describe the bug**
Price impact not loading

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/37959170/209368067-c95f5210-8ad5-4fd9-8092-39be337ad230.png">

**Comment by alexwhte** [comment]
Now it loaded but threw another error 

<img width="1704" alt="image" src="https://user-images.githubusercontent.com/37959170/209368428-50ae533c-7e53-4140-a4e8-7e32c4b4bff9.png">

**Comment by alexwhte** [comment]
<img width="1584" alt="image" src="https://user-images.githubusercontent.com/37959170/209373880-6094c16f-2999-497b-a5fd-96a340f3ee04.png">

Seeing bug on Gnosis USDC pooling

**Comment by just-a-node** [comment]
The major issue here is input normalization for USDC, we need to be converting it to the right decimals.

Similarly for withdraw, the asset/nextAsset amounts are off:
![image](https://user-images.githubusercontent.com/16638982/209375262-39f6c94a-5511-408f-bb98-4324a92fe4b4.png)
