### ISSUE TITLE
Swap UI fail (getBalance?)

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#2857]
**Describe the bug**
Seeing a new bug in Swap UI 
https://d1h9h37hgxfzvk.cloudfront.net/swap/ETH-on-arbitrum?from=WETH

[d1h9h37hgxfzvk.cloudfront.net-1671816680568.log](https://github.com/connext/nxtp/files/10296501/d1h9h37hgxfzvk.cloudfront.net-1671816680568.log)

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/37959170/209376722-b5f92db2-8214-4c8e-8f02-d44e69af0a8b.png">

**Comment by just-a-node** [comment]
Looks fixed - closing
