### ISSUE TITLE
Swap not triggering approval transaction

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#2869]
**Describe the bug**

UI is not sending an approval transaction and instead showing an error that the transfer amount exceeds balanace. The toggle for "infinite approve" is true here.

![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/bff427e8-b363-442c-979d-5fb99da60b21)

**To Reproduce**
1. Go to swap
2. Attempt to swap an asset that isn't approved yet
3. See error, should be an approve txn

**Comment by alexwhte** [comment]
@just-a-node please test
