### ISSUE TITLE
Router volume is incorrect in Explorer

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#2891]
Individual transactions add up to a higher net volume than is shown in Explorer here

https://amarok.connextscan.io/router/0xf26c772c0ff3a6036bddabdaba22cf65eca9f97c
![image](https://user-images.githubusercontent.com/37959170/210029229-8b4467bf-492d-48e1-ab5b-ebf11992841e.png)
![image](https://user-images.githubusercontent.com/37959170/210029233-7fe2c6c5-85eb-4aa0-a681-9e540295d003.png)

First confirm if this a cartographer db issue or an end UI issue?  So that we assign it out correctly

**Comment by pjenviri** [comment]
Fixed. It's a UI issue regarding decimal things.![Screenshot 2565-12-30 at 15.07.32.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/f0e0aea6-e464-4688-a8db-78b055f1523d) Please recheck it.

**Comment by rhlsthrm** [comment]
Confirmed fixed!
