### ISSUE TITLE
Slow path transfers are long-running

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#2912]
**Describe the bug**
About 50+ transfers are past expected TTV 
https://amarok.connextscan.io/transfers

The last successful slow path was earlier today from Ethereum 
https://amarok.connextscan.io/tx/0x4d2a285f4403179aaec28249f691954fa3854a5c92da6b2c7bd467c40ee9c4cc

Per Preetham:
```
connext=> select processed, count(*) from root_messages group by processed;
 processed | count
-----------+-------
 f         |    13
 t         |   153
(2 rows)

connext=> select processed, count(*) from messages group by processed;
 processed | count
-----------+-------
 f         |    89
 t         |   135
(2 rows)
```

**Comment by alexwhte** [comment]
May be related to https://github.com/connext/nxtp/issues/2832

**Comment by rhlsthrm** [comment]
Fixed.
