### ISSUE TITLE
[router] Virtual AMM

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#378]
Create bonding curve function to determine swap rates based on router liquidity. Use the StableSwap contracts here: https://github.com/connext/vector/tree/main/modules/contracts/src.sol/amm.

On receive auction request:
- Query deployed StableSwap contract `onSwapGivenIn` function by using the router's current liquidity for an asset across all chains for the `balances[]`.
- Received amount becomes the following formula: sent amount * AMM swap rate - estimated gas fee (if applicable) - flat fee (0.05%)

Need to test a variety of different liquidity amounts to figure out what the amplification parameter should be.

Tasks:
- [x] Integrate StableSwap contracts into the codebase.
- [x] Make sure unit tests for the contracts are sufficient.
- [x] Integrate router code to query swap rate on auction.
- [x] Unit tests.
- [x] Deploy contract to chain.
- [x] Load tests.

**Comment by LayneHaber** [comment]
No longer relevant.
