### ISSUE TITLE
Reorg handling for carto storage

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#4020]
## Background

We had an issue recently where a Polygon tx got reorged out. We check for safe confirmations on the router side for sending, but not when we query chain data before adding it to cartographer.

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

All chain queries take safe confirmations into account.

## Tasks

- [ ] Update queries to use block numbers with safe confs.

**Comment by alexwhte** [comment]
**Complexity: 8**
  [See the discussion](https://action.parabol.co/meet/mtALUnLIaI/estimate/2) in Sprint Poker #​​31

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by sanchaymittal** [comment]
@rhlsthrm We shouldn't account for safe confirmation while querying data, cause it will add more delay to listing transfers at Explorer.

Rather we can weed out the transfers which don't exist on-chain after a day or manually. Though this task shouldn't be urgent. cc: @alexwhte

**Comment by rhlsthrm** [comment]
Yes good point, we should change this to reflect that we can fix this by using the pending transfers poller to remove old transfers. I'll move to backlog.

**Comment by preethamr** [comment]
Issue seen again today with slowpath prove and process.

**Comment by rhlsthrm** [comment]
Fixed
