### ISSUE TITLE
SDK getAssetEntryFromChaindata returning undefined

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/nxtp#4275]
**Describe the bug**
Utils function from SDK returning `undefined`

**To Reproduce**
1. `import {getAssetEntryFromChaindata} from "@connext/nxtp-utils/dist/helpers"` Add this line for importing the function
2. 
```
const resp = await getAssetEntryFromChaindata("0x7ea6eA49B0b0Ae9c5db7907d139D9Cd3439862a1".toLowerCase(), "1735353714", sdkBase.chainData)
```
- resp returning `undefined`

**Comment by LayneHaber** [comment]
This asset `0x7ea6eA49B0b0Ae9c5db7907d139D9Cd3439862a1` (and other `TEST` deployments) were not included in the chain data prior to https://github.com/connext/chaindata/pull/72 . The sdk utils are working properly.

Closing this issue, but we should not be relying only on chain data for anything. at most it saves an RPC query, but there's no guarantees any asset is present in the json so there should always be fallbacks
