### ISSUE TITLE
[router] Request to Update the Router Address and Assets (Token Smart Contracts) (Omni Team)

### ISSUE THREAD

**Issue by alfredolopez80** [connext/nxtp#457]
Hi, Connext Team, we notice you update the Smart Contract of Transaction Manager in all blockchain, and this requires

- Add Router Address in the New Smart Contract of Transaction Manager
- Add Assets (Token Smart Contract), in Binance Smart Chain and Polygon (at least, waiting for the deployment in Ethereum)

**Information Require**

@Rahul, like a mention yesterday right now i send all Real Token in Production and Mainnet in BSC, Polygon and ETH (Of course in ETH when you deployed not for now), and the Production Router Address (The Old address (0x784CC0dce30BAae1851a7f14b0d19DF3f3a3f30E) in Mainnet must be dropped

Additional share with you again the Security Audit for Certik for you review:
https://www.certik.org/projects/omni

**BSC Token (First Deployed and unique with Vesting and Timelock Process)**

https://bscscan.com/address/0xabc6790673a60b8a7f588450f59d2d256b1aef7f (PROXY ADDRESS)

https://bscscan.com/address/0x1538eec01b7bffbfe268dd4c1242dc1cb7a4803d (Actual Instance)

Code Verified: https://bscscan.com/address/0x1538eec01b7bffbfe268dd4c1242dc1cb7a4803d#code

**Polygon Deployment**

https://polygonscan.com/address/0xabc6790673a60b8a7f588450f59d2d256b1aef7f (PROXY ADDRESS)

https://polygonscan.com/address/0x022aaac040159f142a32cf59ef7241e783c5df71 (Actual Instance)

Code Verified: https://polygonscan.com/address/0x022aaac040159f142a32cf59ef7241e783c5df71#code

**Ethereum Deployment**

https://etherscan.io/address/0xabc6790673a60b8a7f588450f59d2d256b1aef7f (PROXY ADDRESS)

https://etherscan.io/address/0x022aaac040159f142a32cf59ef7241e783c5df71 (Actual Instance)

Code Verified:  https://etherscan.io/address/0x022aaac040159f142a32cf59ef7241e783c5df71#code

Additional the New Addresses of the 
**Router Mainnet and Production environment:**
0x2a3248456464a19fA913bd5dfa952999365b31cE

**Comment by rhlsthrm** [comment]
Added on all networks.
