### ISSUE TITLE
[router] Add config option to disable gas fees for certain asset swaps / chains.

### ISSUE THREAD

**Issue by jakekidd** [connext/nxtp#488]
Currently, gas fees are determined by pulling from oracle deployed on chain, and there is no way to disable this calculation.

In certain cases we may want to disable it, like for TEST tokens on goerli/rinkeby, and if oracle is for some reason unreliable / non-functional for a newly configured / recently minted token on a chain.

I'm getting this error trying to swap TEST tokens in test-ui:
```
[app]         "amount": "500000000000000000",
[app]         "amountReceived": "499750000000000000",
[app]         "gasFeeInReceivingToken": "2388420735747920684"
[app]       },
[app]       "type": "NotEnoughAmount",
[app]       "stack":
[app]           Error: Not enough amount for swap
```
Gas fee is 2.38 TEST, bc exchange rate is not functional for TEST/goerli ETH

This isn't really problematic, just an inconvenience to have to deal with

@rhlsthrm Leaving this assigned to you for now but feel free to reassign. I can even take this on if you'd like.

**Comment by sanchaymittal** [comment]
Closing this, Cause we are using this env as testing.
