### ISSUE TITLE
[router] Certain auction "errors" should be info level.

### ISSUE THREAD

**Issue by jakekidd** [connext/nxtp#489]
See these messages in discord https://discord.com/channels/454734546869551114/901639194869370960/905264521172635718

Basically, if the router has a legitimate reason for rejecting an auction, it should do so without it being considered an error. We should be catching errors like NotEnoughAmount or NotEnoughLiquidity (i.e. if the user doesn't have enough funds or if the router not enough liquidity). Log the occurrence at info level (for the sake of demonstrating that we *are* detecting these auctions), but they shouldn't be labeled as errors, as that will spam the error level in the logs.

@rhlsthrm assigned but feel free to reassign this to me if you'd like!

**Comment by sanchaymittal** [comment]
Updated some logs level in recent releases, closing this issue for now. If we still feel like some logs need some more clarity let's add them specifically in next router log tasks.
