### ISSUE TITLE
[sdk, xpollinate?] Rounding related "JSON-RPC error"

### ISSUE THREAD

**Issue by Tommy-R8** [connext/nxtp#490]
Don't know if anyone's working on this. It's a known issue but haven't seen it here.

It looks like the same error that previously showed "insufficient funds" now causes "JSON-RPC error". Workaround is still the same: deleting a few digits from the end.

**Comment by sanchaymittal** [comment]
issue seems to coming up due to MAX value with native assets, which is resolved on UI.
