### ISSUE TITLE
[sdk, router] Allow a prepare amount to be different than the signed bid

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#511]
Need to modify the SDK to be able to prepare an amount that is different than the quoted bid (can be done by modifying `prepare` to take an extra param for `actualAmount` which is optionally different than the amount. This is used in the case where a swap contract directly calls prepare and the amount is different than the signed bid by the router. The router needs to handle this by allowing a buffer on the signed amount.

**Comment by sanchaymittal** [comment]
closed: https://github.com/connext/nxtp/pull/530
