### ISSUE TITLE
[sdk][router][UI] Error: failed to meet quorum 

### ISSUE THREAD

**Issue by alfredolopez80** [connext/nxtp#516]
Is a constant error received in the console of the UI

`Error: failed to meet quorum (method="getBlockNumber", params={}, results=[{"weight":1,"start":1636598864442,"result":21230908},{"weight":1,"start":1636598864442,"result":21230903},{"weight":1,"start":1636598865261,"result":21175801}], provider={"_isProvider":true,"_events":[],"_emitted":{"block":-2},"formatter":{"formats":{"transaction":{},"transactionRequest":{},"receiptLog":{},"receipt":{},"block":{},"blockWithTransactions":{},"filter":{},"filterLog":{}}},"anyNetwork":false,"_network":{"name":"matic","chainId":137,"ensAddress":null,"_defaultProvider":null},"_maxInternalBlockNumber":21230899,"_lastBlockNumber":-2,"_pollingInterval":4000,"_fastQueryDate":1636598864897,"providerConfigs":[{"provider":{"_isProvider":true,"_events":[],"_emitted":{"block":-2},"formatter":{"formats":{"transaction":{},"transactionRequest":{},"receiptLog":{},"receipt":{},"block":{},"blockWithTransactions":{},"filter":{},"filterLog":{}}},"anyNetwork":false,"_network":{"name":"matic","chainId":137,"ensAddress":null,"_defaultProvider":null},"_maxInternalBlockNumber":21230903,"_lastBlockNumber":-2,"_pollingInterval":4000,"_fastQueryDate":1636598864852,"connection":{"url":"https://polygon-rpc.com/"},"_nextId":107,"_eventLoopCache":{"eth_blockNumber":null},"_internalBlockNumber":{},"_fastBlockNumber":21230903,"_fastBlockNumberPromise":{}},"weight":1,"stallTimeout":750,"priority":1},{"provider":{"_isProvider":true,"_events":[],"_emitted":{"block":-2},"formatter":{"formats":{"transaction":{},"transactionRequest":{},"receiptLog":{},"receipt":{},"block":{},"blockWithTransactions":{},"filter":{},"filterLog":{}}},"anyNetwork":false,"_network":{"name":"matic","chainId":137,"ensAddress":null,"_defaultProvider":null},"_maxInternalBlockNumber":21230908,"_lastBlockNumber":-2,"_pollingInterval":4000,"_fastQueryDate":1636598864693,"connection":{"url":"https://rpc-mainnet.maticvigil.com/"},"_nextId":106,"_eventLoopCache":{"eth_blockNumber":null},"_internalBlockNumber":{},"_fastBlockNumber":21230908,"_fastBlockNumberPromise":{}},"weight":1,"stallTimeout":750,"priority":1},{"provider":{"_isProvider":true,"_events":[],"_emitted":{"block":-2},"formatter":{"formats":{"transaction":{},"transactionRequest":{},"receiptLog":{},"receipt":{},"block":{},"blockWithTransactions":{},"filter":{},"filterLog":{}}},"anyNetwork":false,"_network":{"name":"matic","chainId":137,"ensAddress":null,"_defaultProvider":null},"_maxInternalBlockNumber":21175801,"_lastBlockNumber":-2,"_pollingInterval":4000,"_fastQueryDate":1636598866040,"connection":{"url":"https://matic-mainnet.chainstacklabs.com"},"_nextId":106,"_eventLoopCache":{"eth_blockNumber":null},"_internalBlockNumber":{},"_fastBlockNumber":21175801,"_fastBlockNumberPromise":{}},"weight":1,"stallTimeout":750,"priority":1}],"quorum":1.5,"_highestBlockNumber":21230899,"_internalBlockNumber":{},"_fastBlockNumber":21230899,"_fastBlockNumberPromise":{}}, code=SERVER_ERROR, version=providers/5.5.0)
    at Logger.makeError (vendors~main.chunk.js:33937)
    at Logger.throwError (vendors~main.chunk.js:33947)
    at FallbackProvider.<anonymous> (vendors~main.chunk.js:38444)
    at Generator.next (<anonymous>)
    at fulfilled (vendors~main.chunk.js:37736)`

I guess in important to validate the reason, I'm not sure is a problem with RPC in polygon or Subgraph, but I create this issue for your validation

@rhlsthrm

**Comment by rhlsthrm** [comment]
This is a problem with the polygon RPC. Try changing it or adding more providers to your config.
