### ISSUE TITLE
"Error in subgraph loop" for failed provider call

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#550]
![image](https://user-images.githubusercontent.com/11512787/142957763-dad06e18-5eac-4a0e-a66f-67af92d029e4.png)

The subgraph loop should not cause a full error for a failed RPC call. Users still need to see whatever txs they can.

**Comment by rhlsthrm** [comment]
@jakekidd is this still a thing? Please update or close.

**Comment by jakekidd** [comment]
unsure. going to keep an eye out for it for now, will tack this on to my todo list in the meantime

**Comment by rhlsthrm** [comment]
We can close this when we check health through index node.
