### ISSUE TITLE
[router] Remove amount from labels to values

### ISSUE THREAD

**Issue by SpontaneousOverthrow** [connext/nxtp#559]
**Type**:  Feature request

There are couple of Prometheus metrics such as:
- router_transfer_volume
- router_fees
- router_gas_consumed

All of this metrics have label amount which is string and it is hard to sum this amounts in Grafana/Prometheus.
It will be great if amount will be moved to metric value instead of label.

**Comment by LayneHaber** [comment]
Fixed in #572
