### ISSUE TITLE
[router] Add metric for stacked\failed txns

### ISSUE THREAD

**Issue by SpontaneousOverthrow** [connext/nxtp#569]
Type: feature request
Currently to get information about stuck\failed txns i need to perform request to subgraph so i use custom exporter.
This is critical metric, in future routers can be slashed because of failed tnxs.

```Currently, if a router fails to submit a user's transaction to chain (for whatever reason), then the user's funds are "stuck" until either manual debugging occurs or the transfer expires (after 72 hours). While we plan to penalize cases like this in the future via slashing, in some cases txs can get stuck simply because of irregular chain conditions.```

**Comment by LayneHaber** [comment]
#572 contains updated metrics to address the number of transactions in given [statuses](https://github.com/connext/nxtp/blob/a129e01a6020e0c73e82930e069f51bfa684d0e0/packages/router/src/lib/entities/metrics.ts#L239-L309).

The metric of interest would be number of active transactions (i.e. transactions that you should take action on, but haven't for some reason). and that can be counted by:


```ts
sender_prepared - sender_fulfilled - sender_cancelled
```

- `sender_prepared` -- these are transactions where you have won the bid and the user has deposited funds
- `sender_fulfilled` -- these are transactions that are fully completed and require no further action
- `sender_cancelled` -- these are transactions that were completed and should have all funds released
