### ISSUE TITLE
[sdk] Weighted random bid selection.

### ISSUE THREAD

**Issue by jakekidd** [connext/nxtp#617]
## Summary
As we horizontally scale Connext with more routers, users (i.e. sdks) are going to be selecting bids among a growing number of options. Right now, we select the best price, but there's three central problems to that:
1. Best price is not a guarantee, but an estimate, so there's a margin of error worth accounting for that makes a certain difference between two bids negligible (negligible difference is a function of % margin of error).
2. Many routers will do the same calculation and get the same value for the bid (since there are no vAMMs / swap curves yet)... so we'll pretty much choose the router that responds the quickest (which, over the internet, will often be arbitrary).
3. This does not account for other factors, like the recent behavior and status of this router - i.e. has it been doing receiver prepare quickly? what's the lag between prepare / fulfill like? have all of its recent txs gone through efficiently? how much liquidity does it have (plenty to cover my tx, I hope)? 

For #1 and #2 we'll basically just want to add a degree randomness to bid selection. #3 is more complex and will require a design discussion. We'd need to use subgraph reads to see how quickly txs are going through for that router in recent history, and contract reads for how much **available** (vs in-use) liquidity it has... but we need to balance / weight these factors carefully so as to not exclude *new* routers from the system that have no recent history.

## Importance
Why do we need this issue now? Occasionally, a particular router has an issue. A bug, a weird network problem, etc. This would reduce the number of support cases generated by those routers behaving 'problematically' significantly, and buy us time waiting for the owners to come back online if they are unavailable due to timezone issues (since SDKs will be much less likely to choose a router having *recent* issues).

Also, randomness guarantees we are distributing bids equally

Also, if we consult router *available* liquidity (compared to in-use liquidity) we can alleviate issues with stuck transfers due to routers overbidding as a temporary solution before we have vAMMs

**Comment by jakekidd** [comment]
cc @rhlsthrm @LayneHaber @ArjunBhuptani

**Comment by jakekidd** [comment]
We could also integrate an emergency 'blacklist' for misbehaving routers as a temporary substitute for slashing conditions (and since we're still in early dev phase of the network/protocol).

See relevant emergency 🔥 :
https://discord.com/channels/454734546869551114/852289278876319804/919180488155992094

**Comment by jakekidd** [comment]
@wanglonghong should we close this out?

**Comment by wanglonghong** [comment]
yeah.
