### ISSUE TITLE
[router] Don't bid if RPCs failing 

### ISSUE THREAD

**Issue by LayneHaber** [connext/nxtp#619]
Currently routers can leave users in a `Preparing` state if they cannot get RPC requests/responses to go through. There should be a system to track error rates on RPC calls and refuse to respond to auctions if they are too high (indicating a node has gone down)

**Comment by rhlsthrm** [comment]
Couldn't we do something more simple and just do a simple health check at the time of auction?

**Comment by rhlsthrm** [comment]
Run provider calls to make sure.
