### ISSUE TITLE
[txservice] Fallback not falling back

### ISSUE THREAD

**Issue by wanglonghong** [connext/nxtp#627]
We need to deeply check the working principle of ethers.fallbackprovider and our implementation. 
https://github.com/ethers-io/ethers.js/blob/master/packages/providers/src.ts/fallback-provider.ts#L476

In ethers.fallbackprovider, all the providers should return the result even though it is an error. 
so it can return successful results totally by this line. 
https://github.com/ethers-io/ethers.js/blob/master/packages/providers/src.ts/fallback-provider.ts#L490

we created our SyncProvider by overriding JsonRpcProvider. so we need to deeply check again if it returns results even though it is an error when it throws. 

https://github.com/connext/nxtp/blob/main/packages/txservice/src/shared/syncProvider.ts#L118
https://github.com/connext/nxtp/blob/main/packages/txservice/src/shared/syncProvider.ts#L151
https://github.com/connext/nxtp/blob/main/packages/txservice/src/shared/syncProvider.ts#L155

**Comment by jakekidd** [comment]
> In ethers.fallbackprovider, all the providers should return the result even though it is an error.
so it can return successful results totally by this line.

Yeah, I had the same concern a while back. But if you scan up a few lines, you should have your answer there:
https://github.com/ethers-io/ethers.js/blob/eb432aa1f44ad2cc268d000b266eae9b03db1d17/packages/providers/src.ts/fallback-provider.ts#L482
So, ethers is catching any errors I'm throwing in the `SyncProvider` send method. It throws the first error it gets back if all of the providers respond with an error.
