### ISSUE TITLE
[router][sdk][txservice] Receiving amount utility

### ISSUE THREAD

**Issue by jakekidd** [connext/nxtp#638]
## The Problem
- There is a lot of redundant and misplaced code around fee calculations. All calculations should be stateless methods in utils module.
- Gas fee calculations have some confusing language.
- getSwapRate stub should be in utils module, not in sdk's utils or router's utils
- Also, would be nice to include the math in the "@remarks" section of the function docstrings for calculating all of the needed items. This code needs to be self-documenting / intuitive / maintainable.
- getReceiverAmount also uses some confusing language imo
- All of the fee calc, swap rate, and receiving amount methods should be in one utils file and individually unit tested. Will make debugging a lot easier.

### Example of redundancy in fee calculation
SDK has these methods:
`estimateMetaTxFeeInSendingToken`
`estimateMetaTxFeeInReceivingToken`
`estimateFeeForRouterTransferInSendingToken`
`estimateFeeForRouterTransferInReceivingToken`

SdkBase has:
`getEstimateReceiverAmount`
`estimateFeeForRouterTransfer`
`estimateFeeForMetaTx`
`estimateHardcodedFeeForPrepare`

ChainReader has (and this should def be in utils):
`calculateGasFeeInReceivingToken`
`calculateGasFeeInReceivingTokenForFulfill`
`calculateGasFee` (base method for the two above)

This is already a lot of methods, and offers way more interface than we really need based on use-case. And really, the only use-cases are:
- the SDK calculating the estimated (gas) fees, given no sending amount
- the SDK calculating the estimated received amount, for given sending amount
- the Router calculating the actual received amount to offer in their bid

Another issue I see here: in `SdkBase.getEstimateReceiverAmount`, we are doing math (albeit simple math) such as:
```ts
    // calculate router fee
    const { receivingAmount: swapAmount, routerFee } = await getReceiverAmount(amount, inputDecimals, outputDecimals);
    ...
    const totalGasFee = gasFee.add(relayerFee).add(gasFee);
    const totalFee = totalGasFee.add(routerFee);
    const receiverAmount = BigNumber.from(swapAmount).sub(totalGasFee);
```
(See PR: https://github.com/connext/nxtp/pull/634)
First off, there's some confusing language here. Why is it that we *only* subtract `totalGasFee` ? Well, it's because the routerFee has already been applied in `getReceiverAmount`.

Additionally, we should really delegate all math to the utility itself, and instead supply any/all stateful values needed to do that math to that utility method. Ideally, this would be something like:
```ts
  const { receivingAmount, fees, swapRate, ...rest } = await getReceivingAmount(
    sendingAmount,
    sendingChainId,
    sendingAssetId,
    tokenPriceSendingChain,
    inputDecimals,
    receivingChainId,
    receivingAssetId,
    tokenPriceReceivingChain,
    outputDecimals,
    // ...etc
  );
```

## Proposed Solution
All of the above could be simplified into just one utility method:
```ts
/**
* Calculates gas fees, get vAMM swap rate, and applies router fee. Returns an object with the total receiving amount as well as
* all the details for fees, swap rate, etc.
* 
* If sendingAmount is 0 (which is valid for fee estimation), the
* receiving `amount` will be negative, and only the gas fees will be calculated.
* 
* Additionally, caller should specify which methods to apply relayer fees to.
*
* If router balances aren't supplied, swap rate will default to 1 (which is valid for fee estimation).
*/
getReceivingAmount(
  sendingAmount: BigNumberish,
  sendingChain: ChainInfo,
  sendingAsset: AssetInfo,
  receivingChain: ChainInfo,
  receivingAsset: AssetInfo,
): TransferOutput
```

Types used above:
```ts
type TransferOutput = {
  id: string;                   // Target asset ID, will be redundant but good for sanity check.
  amount: string;         // What the resulting amount will be in target asset, after swap rate and fees are applied.
  swapRate: string;      // Applied vAMM swap rate, if applicable (in fee estimates, this won't be).
  fees:  {
    total: string;            // Amount of asset deducted from initial receiving amount; the sum of everything in `details`.
    details: {
      gas: {
        router: string;     // Amount of asset === value in USD for the gas cost for all router-executed transactions.
        relayer: string;    // Amount of asset === value in USD for the gas cost + relayer fee for all relayer-executed transactions.
      }
      lp: string;              // This is the 0.05% router fee in target asset.
    }
  }
};

type ChainInfo = {
  id: number;
  // Gas price in wei of native token.
  gasPrice: BigNumber;
  // Native token price in USD (wei).
  ethPrice: BigNumber;
};

type AssetInfo = {
  id: number;
  decimals: number;
  // Price in USD (wei).
  price: BigNumber;
};
```

**Comment by jakekidd** [comment]
Started a draft today for something like this:
https://github.com/connext/nxtp/pull/637

**Comment by sanchaymittal** [comment]
This is super helpful!
I was going to cry at some point to clean this up. Thanks for taking initiative.

everything looks good to me, just couple of points:
- maybe need to rename the function to `getSwapAmount` or something getReceivingAmount doesn't sound intuitive.
- fee breakdown should include vAmm rate, which is the same right now. But helps structure updates for the future.

This should most probably align with the new Contracts too, so will save a bunch of time.

**Comment by jakekidd** [comment]
`getSwapAmount` I like where that's headed... also just like `calculateTransfer` or something

Problem with vamm rate being in fees is that fees are a flat subtraction, not a multiplication of the input like amm rate. For example, if the amm rate is 0.93:1.07, I'd imagine that we are multiplying 0.93 * the base amount received (excluding gas fees).

Might be oversimplifying, or just plain wrong lol @LayneHaber lmk
