### ISSUE TITLE
[sdk] Don't expose direct connections to nats/auth when initializing sdk

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/nxtp#64]
Instead of these:
- `natsUrl`: Optional. Override NATS URL otherwise connect to the main, global NATS cluster.
- `authUrl`: Optional. Override auth URL otherwise connect to the main, global auth server.

We should just have a simple:
- `network`: Optional. `testnet` or `mainnet` - defaults to `mainnet`.

Exposing nats/auth will not be backwards compatible when we move to more decentralized messaging and is unnecessary cognitive overhead for the developer.

**Comment by rhlsthrm** [comment]
This isn't for users, but we need a way to override with local stuff.

**Comment by ArjunBhuptani** [comment]
just have a `network` `local` option?

**Comment by rhlsthrm** [comment]
Sure, I'll add that. I think I'll also have an optional override with manual nats/auth url and not expose this to users.

**Comment by rhlsthrm** [comment]
Duplicate of #76
