### ISSUE TITLE
[sdk] Consider renaming `startTransfer` and `finishTransfer` to `prepareTransfer` and `fulfillTransfer`

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/nxtp#65]
Keeping naming consistent is important.

**Comment by LayneHaber** [comment]
It depends on what we want `finishTransfer` to do -- should it *exclusively* call `fulfill`? What about cases where it should be cancelled (i.e. incorrect data put onchain by a malicious router, its expired, etc.)

**Comment by rhlsthrm** [comment]
There's separate functions for cancel. We can't really automate it because it requires user input to sign.

**Comment by LayneHaber** [comment]
Think `prepare` / `fulfill` is a bit annoying for the user (forces knowledge of the protocol they dont necessarily need), but do think the `cancelExpired` definitely has to be renamed

**Comment by LayneHaber** [comment]
That being said, all our events are in `prepare` / `fulfill` syntax so we should keep that consistent
