### ISSUE TITLE
User's signature still revealed after the fulfill call failed on the receiving chain

### ISSUE THREAD

**Issue by FanM** [connext/nxtp#701]
Since the protocol uses the same _user_ signature for **fulfill** call on both chains, there is a chance that the _user_'s fulfill call failed on the receiving chain, say, due to a failure of hash value check (it's likely since _user_ has to hash her arguments and make human errors), the _router_ could use the user's signature to get the fund on the sending chain, at the same time he could call **cancel** on the receiving chain to steal the fund.  Or even worse, if the router happens to be the relayer, he could extract the _user_'s signature and do the things above directly. A malicious _user_ can simultaneously do **fulfill** and **cancel** on both chain as well. 
I think in order to protect the counter-party,  **cancel** should be prohibited once **prepare** has been called by one party, the _user_ can let the transaction expire before calling **fulfill** should she have a second thought. Both parties can retry **fulfill** if there's any human/network error, as long as it's within the expiry window.

Another issue is why the [return value for success](https://github.com/connext/nxtp/blob/main/packages/contracts/contracts/TransactionManager.sol#L851)  is false?

**Comment by rhlsthrm** [comment]
If the user's fulfill fails on the receiving chain, it will necessarily fail on the sending chain, so there's no risk there. 

> the router could use the user's signature to get the fund on the sending chain, at the same time he could call cancel on the receiving chain to steal the fund

This is the exact reason why cancellations are only allowed by the receiving party (i.e. router can only cancel on sending chain, user can only cancel on receiving chain).

Thank you for bringing these up, if we did not consider these cases it would be very bad indeed!

**Comment by FanM** [comment]
>This is the exact reason why cancellations are only allowed by the receiving party (i.e. router can only cancel on sending chain, user can only cancel on receiving chain).

This still troubles me as cancellation only renounces the right for the receiving party, instead of  giving them more protection. e.g. If a _user_ sends a signed transaction to a relayer (_router_) but the relayer maliciously returned an error message to the _user_, the _user_ assumes the transaction failed and calls **cancel** on the receiving chain, effectively getting rid of her right to receive the fund. Then later the _router_ can use the valid signature to get the fund from the sending chain.

**Comment by FanM** [comment]
If the user is using a dapp that's built on this protocol and she doesn't have any gas on the receiving chain (which is why she chose a relayer), how would she simulate the transaction? On the other hand, the dapp could start cheating only when it sees the asset amount is big enough, and pass any testing on small amount. I think the **cancel** function should be removed entirely to provide more safety to both parties. If the relayer refuses to fulfill the transaction once it got the user signature, the user could choose another relayer, as long as the transaction is within the expiry window. Since all transactions are time-locked, the cancellation logic is embedded inherently.

**Comment by rhlsthrm** [comment]
You can estimateGas without gas, just by using a read-only provider. I tested this myself:
```js
const e = require("ethers")
const p = e.getDefaultProvider("rinkeby")
p.estimateGas({to: "0xfAFbdbD6358345bcDB606588b695e1B97f28021e", data: "0xd09de08a" }).then(c => console.log(c))

// returns
BigNumber { _hex: '0x6f23', _isBigNumber: true }
```

The cancellation logic is provided to protect users against routers preparing an invalid amount or some other case where they don't need to wait 72 hours for expiry.
