### ISSUE TITLE
[chainData] Add info to chainData

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#743]
Need the following items in chainData:
```
# Gas
gasPriceMinimum
gasPriceMaximum
gasPriceMultiplier // in case we need to multiply the received price, i.e. Arbitrum
lowGasThreshold

# Subgraph
subgraphSyncBuffer
subgraphs (array of { subgraphUrl, healthUrl })

# Relayer
gelatoUrl
```

One good thing would be to migrate this to a new repo to remove it from the AnySwap stuff. This way we can keep the old format for routers that haven't updated yet.

Schema for subgraphs:

```json
{
  "subgraphs": [{
    "runtime": {
      "query": "...",
      "health": "...",
    },
    "analytics": {
      "query": "...",
      "health": "...",
    }
  }]
}
```
Health endpoint mapping is here: https://github.com/connext/subgraph-cache-server/blob/main/src/manualDeps.ts#L41

**Comment by sanchaymittal** [comment]
done
