### ISSUE TITLE
[contracts] Top-level batching

### ISSUE THREAD

**Issue by liu-zhipeng** [connext/nxtp#768]
### Discussed in https://github.com/connext/nxtp/discussions/757

<div type='discussions-op-text'>

<sup>Originally posted by **LayneHaber** January 17, 2022</sup>
## Summary
Allowing batching to happen natively within the `TransactionManager` opens up more effective gas optimizations.  

## Motivation
Gas costs can be heavily optimized for transactions if routers are able to batch them safely. By using the [Multicall by OZ](https://docs.openzeppelin.com/contracts/4.x/utilities#multicall) contract, multiple functions may be called simultaneously while preserving any `msg.sender` properties (as the contract uses `delegatecall`).

## Proposed Solution
The `TransactionManager` should inherit the `Multicall` contract so that there is a `.multicall(data)` function on the contract itself.

```ts
import "@openzeppelin/contracts/utils/Multicall.sol";

contract TransactionManager is Multicall { ... }
```

## Test Cases
The following should be implemented:

```ts
it("should succeed for other transfers if one call reverts", () => { ... })
it("should work for multiple fulfills", () => { ... })
it("should work for multiple cancels", () => { ... })
it("should work for multiple prepares", () => { ... })
it("should work for a mix of calls", () => { ... })
```

## Outstanding Questions

None

## PsuedoCode 

import "@openzeppelin/contracts/utils/Multicall.sol";

contract TransactionManager is Multicall { ... }

## Tasks

- Implement inheritance
- Add test cases</div>

**Comment by LayneHaber** [comment]
Closed in favor of up to date issue
