### ISSUE TITLE
[contracts] Explore adding aave portal collateral

### ISSUE THREAD

**Issue by LayneHaber** [connext/nxtp#821]
The outcome of this issue should be a spec that is detailed breakdown of how to implement and accomplish this

**Comment by jakekidd** [comment]
I'm going to spend some time today or tomorrow working on my proposal for a *potential* way to get this to be less trusty

WIP. Not worth a read just yet https://www.notion.so/connext/Warrant-Backed-Loans-ba908bf6e8df4fd4b4db6ca5c95a3b4e

**Comment by LayneHaber** [comment]
See the discussion comments in #939

**Comment by LayneHaber** [comment]
(closing as the idea is going to be converted into a spec today)
