### ISSUE TITLE
[contracts] Figure out why relayer fee is weird

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#835]
On test transactions, relayer fee seems to be 0 always.

Edit: It wasn't actually 0 but it was something very small on a successful tx: https://dashboard.tenderly.co/tx/rinkeby/0x051e8efc8470d34a23401f982298a62544b4349a100a68c957523b6d12164cce

**Comment by LayneHaber** [comment]
What exists is a placeholder, need a formal relayer fee spec. Won't fix
