### ISSUE TITLE
[sequencer] update sequencer business logic from pub-sub to polling for bestBid selection.

### ISSUE THREAD

**Issue by sanchaymittal** [connext/nxtp#845]
More to scope for this task:
- function in auctionCache to fetch the transactionIds with pending status.
- function to update status for bids:transactionIds:* in a function call.

For reference to business logic for implementation refer to sequencer/operations/bid code.

**Comment by base0010** [comment]
Added two functions for this `getAllTransactionsIdsWithPendingBids()` and `updateAllBidsWithTransactionId` in the auctions cache class. Need to write unit tests.

**Comment by sanchaymittal** [comment]
Done
