### ISSUE TITLE
[txservice] Confirmations not accepted in config

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#91]
Txservice seems to hardcode the confirmations to wait to 1. This should be a configurable option, per chain. The router already has a config option for confirmations, so this should be passed through to the tx service.

**Comment by jakekidd** [comment]
Hey @rhlsthrm are you seeing this in the code itself, or based on some behavior? The option should be configurable

**Comment by jakekidd** [comment]
We do initially wait for 1 confirmation, timing out after a certain period of time (default I think is 30s). But once we get the 1 confirmation, we then wait for the desired number of confirmations in ChainConfig.confirmations

**Comment by rhlsthrm** [comment]
Ah okay, I may have misread then. If you see that the config is passed through properly from the router, we can close this.
