### ISSUE TITLE
[ops] Run LogDNA in cluster

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#920]
We have been using LogDNA and the logging format makes debug/viewing logs easier than the AWS setup. We should hook up LogDNA so we can have access to our old workflows.

**Comment by carlomazzaferro** [comment]
I take it back, it might be possible to get this done: https://www.kartar.net/2017/10/sending-logs-from-aws-ecs-using-logspout/ 

Will give this a try

**Comment by carlomazzaferro** [comment]
Never mind, not possible. Can't access the docker.sock from host in Fargate.
