### ISSUE TITLE
[ops] Providers need to be passed in as a secret

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#943]
https://github.com/connext/nxtp/blob/amarok/ops/testnet/config.tf#L10

We should never keep providers as plaintext. Also since it's an array we need the ability to pass in N number of providers through the secret. Not sure the best way to do that with Terraform, maybe we have to pass in a comma-separated string and parse it in TF.

**Comment by carlomazzaferro** [comment]
https://github.com/connext/nxtp/pull/949
