### ISSUE TITLE
[subgraph] unit test

### ISSUE THREAD

**Issue by sanchaymittal** [connext/nxtp#957]

**Comment by alexwhte** [comment]
@sanchaymittal Does this issue cover unit test coverage for all packages? or something else
Working to ensure we cover that somewhere (if not here)

**Comment by rhlsthrm** [comment]
> @sanchaymittal Does this issue cover unit test coverage for all packages? or something else Working to ensure we cover that somewhere (if not here)

We have unit tests everywhere already, I think this is the final module that needs tests. We should probably close this for now and reopen when we have a better idea of what the blockers are.
