### ISSUE TITLE
[subgraph] Subgraph optimization/refactor

### ISSUE THREAD

**Issue by jakekidd** [connext/nxtp#967]
Goal: reduce subgraph queries significantly.

Right now, every polling loop we make 1 query per domain (to retrieve all XCalls) and 1 query per XCall for its corresponding destination Transfer object; that's O(n^2). Let's see if we can bring down #calls to be linear based on # of domains.

There are two components needed to accomplish this.
1. Off-chain: how do we reduce the # of queries we're sending?
2. On-chain (or rather on-subgraph), how do we index our data to make querying lighter?

## 1. Reduce queries, how do?
The query for XCalls is fine. The query for Executed/Reconciled could be polished.

For the router, we aren't really concerned with whether a Transfer was Executed *or* Reconciled, we're only concerned with whether or not the Executed/Reconciled entry *exists* (on the destination domain). Routers want to know if the transfer has 'already happened'; the existence of an entry on destination domain indicates that there's no reason for them to bid on that Transfer.

With this in mind, we should only be focused on updating the status in the router cache to label that Transfer as unavailable for auctions/no longer pending.

How do?:
a) Instead of querying *individually* by transfer ID, query for Executed/Reconciled Transfers by transfer **IDs**, passing in multiple IDs at once and making only 1 single query.
b) Query by >block number (or block timestamp). Use the block number or timestamp as an index from which to start (similar to nonce). Once we have all the Executed/Reconciled Transfers up to block number 40, we can start at block number 40 for all our subsuquent requests.... given that we should definitely leave some "wiggle-room" for re-orgs! Maybe why we should go with timestamps, not block number?

## 2. Reduce complexity, how do?
The other component here is we want to make the subgraph a bit simpler to query. Something I've noticed here is that there's actually __no reason to have xcalled Transfers and Executed/Reconciled Transfers be the same thing__.

We should split the subgraph entity Transfer into two separate entities. One entity would be the origin chain `XCall`. The other would be the destination chain `XFulfill` (or something like that, as it would have both executed and reconciled info).

My thinking here is that, as it is, every Transfer already falls into one of these two categories. Nowhere on the subgraph will you find a Transfer with both the xcalled and the executed/reconciled properties filled out... so maybe we could remove status from the equation, take out all these params filled with `null`, and just have separate entities.

PROs:
  - `XFulfill` wouldn't need to record nonce (could record index instead? hmm)
  - `status` is obsolete on both
  - say bye to all the `null`s
  - you could remove `originDomain` from `XCall` entity and `destinationDomain` from `XFulfill`
  - __we could collate both into an `XTransfer` object in the cache anyway__
  - router could now query by `getXCallsFromNonce`, not `getTransfersThatAreAlsoXCallsFromNonce`

CONs:
  - aint none

Here's the proposed schemas for `XCall` and `XFulfill`:
```
type XCall @entity {
  id: ID!
  destination: BigInt
  chainId: BigInt

  # Transfer Data
  to: Bytes
  transferId: Bytes
  callTo: Bytes
  callData: Bytes
  router: Router

  # Index
  nonce: BigInt

  # Asset
  transferAsset: Bytes
  localAsset: Bytes

  # Amount
  transferAmount: BigInt
  localAmount: BigInt

  # Transaction
  caller: Bytes
  transactionHash: Bytes
  timestamp: BigInt
  gasPrice: BigInt
  gasLimit: BigInt
  blockNumber: BigInt
}

type XFulfill @entity {
  id: ID!
  origin: BigInt
  chainId: BigInt

  # Transfer Data
  to: Bytes
  transferId: Bytes
  callTo: Bytes
  callData: Bytes
  router: Router

  # Index
  nonce <or index?>: BigInt

  # Asset
  transferAsset: Bytes
  localAsset: Bytes

  # Amount
  transferAmount: BigInt
  executeLocalAmount: BigInt
  reconcileLocalAmount: BigInt

  # Execute Transaction
  executeCaller: Bytes
  executeTransactionHash: Bytes
  executeTimestamp: BigInt
  executeGasPrice: BigInt
  executeGasLimit: BigInt
  executeBlockNumber: BigInt

  # Reconcile Transaction
  reconcileCaller: Bytes
  reconcileTransactionHash: Bytes
  reconcileTimestamp: BigInt
  reconcileGasPrice: BigInt
  reconcileGasLimit: BigInt
  reconcileBlockNumber: BigInt
}
```

**Comment by sanchaymittal** [comment]
good idea!

**Comment by jakekidd** [comment]
Other changes made:
- Naming in the schema:
  - Removed `reconciledLocalAsset` and `executedLocalAsset`. While it's possible for the reconcile local amount and execute local amount to be different, the asset will always be the same. We now call this `localAsset`.
  - Removed `transacting` in favor of `transfer`
  - Changed `executed` and `reconciled` to `execute` and `reconcile`, reads a bit better.

Other changes that we might want to throw in here:
- Fix the `Executed` event to have an array of routers in place of just 1 router. Update the `emit` to use the array of routers as the parameter.

**Comment by rhlsthrm** [comment]
The query optimizations are in here: https://github.com/connext/nxtp/pull/930

**Comment by sanchaymittal** [comment]
done in #1076
