### ISSUE TITLE
[contracts] Router metatx signature

### ISSUE THREAD

**Issue by jakekidd** [connext/nxtp#968]
Since we'll be eliminating the relayer fee signature in #900, there will no longer be any security measures preventing the sequencer/relayer from sending whatever execute tx params to chain that they like. Obviously this isn't of any major concern operating on testnets, but would be good to get this critical piece of tech debt out of the way (or at the very least, leave some room for the final implementation in the future).

In order to be certain that the router has consented to executing a transfer with the amount specified, the router who is LPing must sign a hash of the ExecuteArgs. We'll need to pass in this signature, and recover it on chain to be sure it came from the router.

The signature must include the router array length (indicating what level of multipath transfer the router consents to) and include the transfer ID. Here is the draft of the signed content:
```solidity
  /**
   * @notice The permit represents the router's consent to use its funds to `execute` a transfer. This
   * information should be hashed and signed by each router in the routers array individually.
   * @param params - The CallParams. These are consistent across sending and receiving chains.
   * @param local - The local asset for the transfer, will be swapped to the adopted asset if
   * appropriate
   * @param round - The length of the routers array. Indicates how many routers this router assents to
   * conducting a multipath transfer with.
   * @param originSender - The sender of the transfer on the origin chain (i.e. the user, but not
   * necessarily the xcaller).
   */
  struct RouterPermit {
    bytes transferId;
    CallParams params;
    address local;
    uint16 round;
    address originSender;
  }
  ```

**Comment by LayneHaber** [comment]
closing, not relevant. by signing bid lengths and transfer ids all signatures are unique
