### ISSUE TITLE
[contracts] Combine `StableSwap` and `Connext`

### ISSUE THREAD

**Issue by LayneHaber** [connext/nxtp#970]
Having the stable swap as a separate contract increases the cost of gas by a large margin (includes an `approve`, `transferFrom`, and a `transfer`) on both `xcall` and `execute`.

Instead, there should be an *option* to add an external pool, but the default should be to have the stable swap liquidity be added on the `Connext` contract.

**Comment by liu-zhipeng** [comment]
Implemented by `StableSwapFacet`!!
