### ISSUE TITLE
As a user the cache should only store necessary data

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#975]
We have talked about ways to remove old data from the cache. In reality the cache only needs to store the most recent xcalled transfer for each domain, just so it has a place to start a new subgraph query from.

**Comment by base0010** [comment]
Seems using some of the utility functions in /cache/transfers.ts like removePending() to achieve this. Question is where the hook should be, or should it be polled.

**Comment by rhlsthrm** [comment]
Can the hook be on the add/update functions?

**Comment by base0010** [comment]
https://github.com/connext/nxtp/pull/1231 cant figure out how to change the linked PR

**Comment by alexwhte** [comment]
i did it manually here, if that's what you meant @base0010 
![image](https://user-images.githubusercontent.com/37959170/170737878-aed75356-d741-4f0d-ad0a-6d1dfc536635.png)
