### ISSUE TITLE
[subgraph] Explore using graphqlclient

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#988]
https://github.com/graphprotocol/graph-client

The Graph has released a client tool which has a lot of the features we need including:
- Fallback subgraphs
- Autogenerated TS types
- Subgraph stitching (WIP but they want to help us with this)

This task is to explore what we can do with this and break it down into actual work tasks.

**Comment by wanglonghong** [comment]
The blocker is that graphclient doesn't have the strategy that we want right now.  so contacting to graphql tech guys to have this feature.
